// ── Chapter 02 — Core Language ──────────────────────────────────────────────
QUESTIONS["02"] = [
  {
    q: "What does print('a', 'b', sep='-') output?",
    options: ["a b", "a-b", "ab", "a - b"],
    answer: 1,
    explain: "The `sep` argument sets the string placed between the printed items. With sep='-' the two items are joined by a hyphen: a-b.",
  },
  {
    q: "By default, what character does print() add at the end of its output?",
    options: ["A space", "A newline (\\n)", "A tab", "Nothing"],
    answer: 1,
    explain: "print() ends with a newline by default (end='\\n'). You can change it, e.g. print('x', end='') to stay on the same line.",
  },
  {
    q: "How do you write a single-line comment in Python?",
    options: ["// comment", "/* comment */", "# comment", "-- comment"],
    answer: 2,
    explain: "Python comments start with `#` and run to the end of the line. There is no dedicated multi-line comment syntax (triple-quoted strings are sometimes used instead).",
  },
  {
    q: "Which is a valid variable name in Python?",
    options: ["2nd_place", "total-score", "_count", "class"],
    answer: 2,
    explain: "Names must start with a letter or underscore and contain only letters, digits, and underscores. `2nd_place` starts with a digit, `total-score` has a hyphen, and `class` is a reserved keyword.",
  },
  {
    q: "What is the result of type(3.0)?",
    options: ["<class 'int'>", "<class 'float'>", "<class 'number'>", "<class 'str'>"],
    answer: 1,
    explain: "A literal with a decimal point is a float. type(3.0) returns <class 'float'>.",
  },
  {
    q: "What does the expression 7 // 2 evaluate to?",
    options: ["3.5", "3", "4", "1"],
    answer: 1,
    explain: "`//` is floor division: it divides and rounds toward negative infinity, giving the integer 3 here.",
  },
  {
    q: "What does 2 ** 3 evaluate to?",
    options: ["6", "8", "9", "5"],
    answer: 1,
    explain: "`**` is exponentiation. 2 ** 3 is 2 to the power 3 = 8.",
  },
  {
    q: "What does 17 % 5 evaluate to?",
    options: ["2", "3", "3.4", "0"],
    answer: 0,
    explain: "`%` is the modulo (remainder) operator. 17 divided by 5 is 3 remainder 2, so 17 % 5 is 2.",
  },
  {
    q: "What is the value and type returned by input()?",
    options: [
      "Always an int",
      "Always a str (string)",
      "A float",
      "It depends on what the user types",
    ],
    answer: 1,
    explain: "input() always returns a string. To do arithmetic you must convert, e.g. int(input()) or float(input()).",
  },
  {
    q: "What does int('42') return?",
    options: ["'42'", "42", "42.0", "An error"],
    answer: 1,
    explain: "int('42') parses the numeric string and returns the integer 42.",
  },
  {
    q: "What does float(5) return?",
    options: ["5", "'5.0'", "5.0", "An error"],
    answer: 2,
    explain: "float(5) converts the integer 5 to the floating-point value 5.0.",
  },
  {
    q: "Which operator checks equality of value in Python?",
    options: ["=", "==", "===", "!="],
    answer: 1,
    explain: "`==` compares values for equality. A single `=` is assignment, and `!=` is 'not equal'. Python has no `===`.",
  },
  {
    q: "What is the result of 3 < 5 and 5 < 4?",
    options: ["True", "False", "An error", "None"],
    answer: 1,
    explain: "3 < 5 is True but 5 < 4 is False; True and False is False. `and` requires both sides to be truthy.",
  },
  {
    q: "What does the expression 'Py' + 'thon' produce?",
    options: ["'Python'", "'Py thon'", "'Pythhon'", "An error"],
    answer: 0,
    explain: "The `+` operator concatenates strings, joining them end to end to give 'Python'.",
  },
  {
    q: "What does 'ab' * 3 produce?",
    options: ["'ababab'", "'ab ab ab'", "'ab3'", "An error"],
    answer: 0,
    explain: "Multiplying a string by an integer repeats it. 'ab' * 3 gives 'ababab'.",
  },
  {
    q: "What is s[0] if s = 'Python'?",
    options: ["'P'", "'y'", "'n'", "0"],
    answer: 0,
    explain: "Indexing is zero-based, so s[0] is the first character, 'P'.",
  },
  {
    q: "What does s[-1] return for s = 'Python'?",
    options: ["'P'", "'n'", "'o'", "An error"],
    answer: 1,
    explain: "Negative indices count from the end; -1 is the last character, 'n'.",
  },
  {
    q: "What does 'Hello'.upper() return?",
    options: ["'hello'", "'HELLO'", "'Hello'", "'hELLO'"],
    answer: 1,
    explain: ".upper() returns a new string with all characters uppercased: 'HELLO'. Strings are immutable, so the original is unchanged.",
  },
  {
    q: "What does '  hi  '.strip() return?",
    options: ["'hi'", "'  hi  '", "'hi  '", "'  hi'"],
    answer: 0,
    explain: ".strip() removes leading and trailing whitespace, returning 'hi'.",
  },
  {
    q: "What does 'a,b,c'.split(',') return?",
    options: ["'abc'", "['a', 'b', 'c']", "('a','b','c')", "'a b c'"],
    answer: 1,
    explain: ".split(',') breaks the string at each comma and returns a list of the pieces: ['a', 'b', 'c'].",
  },
  {
    q: "Given name = 'Sam', what does f'Hi {name}' produce?",
    options: ["'Hi {name}'", "'Hi Sam'", "'Hi name'", "An error"],
    answer: 1,
    explain: "An f-string evaluates the expression inside {} and inserts its value, giving 'Hi Sam'.",
  },
  {
    q: "What does f'{3.14159:.2f}' produce?",
    options: ["'3.14159'", "'3.14'", "'3.142'", "'3'"],
    answer: 1,
    explain: "The format spec `.2f` formats the number as fixed-point with 2 decimal places: '3.14'.",
  },
  {
    q: "Which values are considered 'falsy' in Python?",
    options: [
      "Only False",
      "0, '', [], {}, None, and False",
      "Any negative number",
      "Only None",
    ],
    answer: 1,
    explain: "Falsy values include False, None, numeric zero, and empty containers ('', [], {}, set()). Everything else is truthy.",
  },
  {
    q: "What is the result of bool('')?",
    options: ["True", "False", "''", "An error"],
    answer: 1,
    explain: "An empty string is falsy, so bool('') is False. A non-empty string like bool('a') is True.",
  },
  {
    q: "What does None represent in Python?",
    options: [
      "The number zero",
      "An empty string",
      "The absence of a value (a null-like singleton)",
      "A syntax error",
    ],
    answer: 2,
    explain: "None is a special singleton object representing 'no value'. Functions that don't return anything return None.",
  },
  {
    q: "How should you test whether x is None?",
    options: ["x == None", "x is None", "x = None", "None(x)"],
    answer: 1,
    explain: "Use `x is None`. `is` checks identity, and None is a unique singleton, so `is None` is the idiomatic and reliable test.",
  },
  {
    q: "What does 5 + 2.0 evaluate to, and what type?",
    options: ["7 (int)", "7.0 (float)", "'7.0' (str)", "An error"],
    answer: 1,
    explain: "Mixing int and float promotes the result to float (implicit widening), so 5 + 2.0 is 7.0.",
  },
  {
    q: "What is the result of int(3.9)?",
    options: ["4", "3", "3.9", "An error"],
    answer: 1,
    explain: "int() truncates toward zero (it does not round), so int(3.9) is 3.",
  },
  {
    q: "What does len('Python') return?",
    options: ["5", "6", "7", "'Python'"],
    answer: 1,
    explain: "len() returns the number of characters. 'Python' has 6 characters.",
  },
  {
    q: "Which operator is the identity operator?",
    options: ["==", "is", "in", "="],
    answer: 1,
    explain: "`is` tests object identity (whether two names refer to the same object). `==` tests value equality, and `in` tests membership.",
  },
  {
    q: "What does the walrus-free expression 10 == '10' evaluate to?",
    options: ["True", "False", "An error", "None"],
    answer: 1,
    explain: "An int and a str are never equal in Python, so 10 == '10' is False. You'd need to convert one side first.",
  },
  {
    q: "What does 'Age: ' + str(30) produce?",
    options: ["'Age: 30'", "'Age: '30", "An error (can't add str and int)", "'Age30'"],
    answer: 0,
    explain: "You cannot concatenate a str and int directly, so str(30) converts 30 to '30' first, yielding 'Age: 30'.",
  },
];
