// ── Chapter 04 — Functions · expansion pool ─────────────────────────────────
QUESTIONS["04"].push(
  {
    q: "What does this return?  def f(): pass\\nprint(f())",
    options: ["pass", "None", "0", "Error"],
    answer: 1,
    explain: "A function whose body is just `pass` returns None implicitly, so it prints None.",
  },
  {
    q: "What is the output?  def f(a, b=10): return a + b\\nprint(f(5))",
    options: ["5", "15", "10", "Error"],
    answer: 1,
    explain: "b defaults to 10 when omitted, so f(5) returns 5 + 10 = 15.",
  },
  {
    q: "What is the output?  def f(a, b=10): return a + b\\nprint(f(5, 20))",
    options: ["15", "25", "35", "Error"],
    answer: 1,
    explain: "The explicit 20 overrides the default, so f(5, 20) returns 25.",
  },
  {
    q: "Which call passes b by keyword?  def f(a, b): ...",
    options: ["f(1, 2)", "f(a=1, b=2)", "f(1, b=2)", "Both b and c"],
    answer: 2,
    explain: "f(1, b=2) passes a positionally and b as a keyword. (f(a=1, b=2) passes both by keyword.)",
  },
  {
    q: "Can a positional argument follow a keyword argument in a call, e.g. f(a=1, 2)?",
    options: [
      "Yes, always",
      "No — SyntaxError: positional argument follows keyword argument",
      "Only inside a class",
      "Only for *args",
    ],
    answer: 1,
    explain: "Once you use a keyword argument, all following arguments must also be keywords; otherwise it's a SyntaxError.",
  },
  {
    q: "What does f(*[1, 2, 3]) do when calling def f(a, b, c)?",
    options: [
      "Passes the list as a itself",
      "Unpacks the list into positional arguments a=1, b=2, c=3",
      "Errors",
      "Passes a=[1,2,3]",
    ],
    answer: 1,
    explain: "The * in a call unpacks the iterable into separate positional arguments.",
  },
  {
    q: "What does f(**{'a': 1, 'b': 2}) do for def f(a, b)?",
    options: [
      "Passes a dict as a",
      "Unpacks the dict into keyword arguments a=1, b=2",
      "Errors",
      "Ignores the dict",
    ],
    answer: 1,
    explain: "The ** in a call unpacks a mapping into keyword arguments matching parameter names.",
  },
  {
    q: "In def f(a, b, *, c), what is special about c?",
    options: [
      "It's optional",
      "It's keyword-only — must be passed as c=value",
      "It collects extra args",
      "It's positional-only",
    ],
    answer: 1,
    explain: "Parameters after a bare * are keyword-only; c must be given by name, not positionally.",
  },
  {
    q: "What does the / in def f(a, b, /, c) indicate?",
    options: [
      "Division",
      "a and b are positional-only (can't be passed by keyword)",
      "c is required",
      "A syntax error",
    ],
    answer: 1,
    explain: "Parameters before a / are positional-only — they cannot be supplied using their names.",
  },
  {
    q: "What is a closure?",
    options: [
      "A closed file",
      "A nested function that captures variables from its enclosing scope",
      "A loop that never ends",
      "A type of exception",
    ],
    answer: 1,
    explain: "A closure is an inner function that remembers and accesses names from the scope where it was defined, even after that scope returns.",
  },
  {
    q: "What does this print?  def outer(x):\\n    def inner():\\n        return x * 2\\n    return inner\\nprint(outer(5)())",
    options: ["10", "5", "inner", "Error"],
    answer: 0,
    explain: "outer(5) returns the closure inner, which captured x=5; calling it returns 5 * 2 = 10.",
  },
  {
    q: "What does the `nonlocal` keyword do?",
    options: [
      "Creates a global variable",
      "Lets an inner function rebind a variable from the enclosing (non-global) function scope",
      "Deletes a variable",
      "Imports a module",
    ],
    answer: 1,
    explain: "nonlocal binds to a variable in the nearest enclosing function scope, allowing an inner function to modify it.",
  },
  {
    q: "What is recursion?",
    options: [
      "A loop keyword",
      "A function calling itself to solve a smaller subproblem",
      "Importing a module twice",
      "A type of list",
    ],
    answer: 1,
    explain: "Recursion is when a function calls itself, typically reducing the problem toward a base case that stops the recursion.",
  },
  {
    q: "What must every recursive function have to avoid infinite recursion?",
    options: [
      "A global variable",
      "A base case that returns without recursing",
      "A while loop",
      "A decorator",
    ],
    answer: 1,
    explain: "A base case terminates the recursion; without it, calls stack until Python raises RecursionError.",
  },
  {
    q: "What does this factorial return?  def fact(n): return 1 if n <= 1 else n * fact(n-1)\\nfact(4)",
    options: ["24", "12", "4", "10"],
    answer: 0,
    explain: "4*3*2*1 = 24. The base case (n <= 1) returns 1 and stops the recursion.",
  },
  {
    q: "What does map(str, [1, 2, 3]) produce when listed?",
    options: ["['1','2','3']", "[1,2,3]", "'123'", "[str, str, str]"],
    answer: 0,
    explain: "map applies the function to each item lazily; list()-ed it gives ['1','2','3'].",
  },
  {
    q: "What does list(filter(lambda x: x > 2, [1,2,3,4])) return?",
    options: ["[3, 4]", "[1, 2]", "[1,2,3,4]", "[True, True]"],
    answer: 0,
    explain: "filter keeps items where the predicate is truthy; only 3 and 4 are > 2.",
  },
  {
    q: "What does functools.reduce(lambda a,b: a+b, [1,2,3,4]) compute?",
    options: ["10", "24", "[1,2,3,4]", "4"],
    answer: 0,
    explain: "reduce folds the list left-to-right with the function, summing to 1+2+3+4 = 10.",
  },
  {
    q: "What is a higher-order function?",
    options: [
      "A function with many lines",
      "A function that takes and/or returns other functions",
      "A recursive function",
      "A built-in only",
    ],
    answer: 1,
    explain: "Higher-order functions operate on functions — taking them as arguments (map, filter, sorted key) or returning them.",
  },
  {
    q: "What does a decorator do?",
    options: [
      "Formats output",
      "Wraps a function to extend/modify its behavior without changing its code",
      "Deletes a function",
      "Documents a function",
    ],
    answer: 1,
    explain: "A decorator is a callable that takes a function and returns a new function, adding behavior (logging, timing, caching) around it.",
  },
  {
    q: "What syntax applies a decorator named log to a function?",
    options: ["@log above the def", "log() inside the def", "#log", "decorate log"],
    answer: 0,
    explain: "The @log line directly above `def f(): ...` is sugar for f = log(f).",
  },
  {
    q: "What does the type annotation in def f(x: int) -> str do at runtime?",
    options: [
      "Enforces types and errors on mismatch",
      "Nothing by default — it's a hint for readers/tools, not enforced",
      "Converts x to int",
      "Makes the function faster",
    ],
    answer: 1,
    explain: "Annotations document intended types and help tools like mypy, but Python does not enforce them at run time.",
  },
  {
    q: "What is a 'pure function'?",
    options: [
      "A function with no parameters",
      "A function whose output depends only on inputs and which has no side effects",
      "A built-in function",
      "A recursive function",
    ],
    answer: 1,
    explain: "Pure functions return the same result for the same inputs and don't mutate external state — easy to test and reason about.",
  },
  {
    q: "What does this print?  x = 10\\ndef f():\\n    x = 20\\nf()\\nprint(x)",
    options: ["20", "10", "None", "Error"],
    answer: 1,
    explain: "The assignment inside f creates a local x; the module-level x stays 10.",
  },
  {
    q: "What does this print?  x = 10\\ndef f():\\n    global x\\n    x = 20\\nf()\\nprint(x)",
    options: ["10", "20", "None", "Error"],
    answer: 1,
    explain: "`global x` makes the assignment rebind the module-level variable, so x becomes 20.",
  },
  {
    q: "What does def f(*args): return len(args) return for f(1, 2, 3)?",
    options: ["1", "3", "6", "(1,2,3)"],
    answer: 1,
    explain: "args collects the three positional arguments into a tuple of length 3.",
  },
  {
    q: "What does def f(**kw): return list(kw) return for f(a=1, b=2)?",
    options: ["[1, 2]", "['a', 'b']", "[('a',1),('b',2)]", "2"],
    answer: 1,
    explain: "kw is a dict {'a':1,'b':2}; list(kw) gives its keys ['a', 'b'].",
  },
  {
    q: "In def f(a, *args, **kwargs), what order must these appear?",
    options: [
      "kwargs, args, a",
      "positional params, then *args, then **kwargs",
      "any order",
      "*args must be last",
    ],
    answer: 1,
    explain: "The required order is normal parameters, then *args, then **kwargs.",
  },
  {
    q: "What does return with no value do?",
    options: [
      "Returns 0",
      "Exits the function returning None",
      "Raises an error",
      "Continues execution",
    ],
    answer: 1,
    explain: "A bare `return` exits the function immediately and yields None.",
  },
  {
    q: "What does this unpack?  def stats(): return 1, 2, 3\\na, b, c = stats()",
    options: [
      "a=(1,2,3)",
      "a=1, b=2, c=3",
      "Error",
      "a=1 only",
    ],
    answer: 1,
    explain: "The function returns a tuple (1, 2, 3) which unpacks into a=1, b=2, c=3.",
  },
  {
    q: "What is the safe pattern for a mutable default argument?",
    options: [
      "def f(x=[]):",
      "def f(x=None): if x is None: x = []",
      "def f(x={}):",
      "def f(x=list):",
    ],
    answer: 1,
    explain: "Use None as the default and create a fresh list inside, avoiding the shared-mutable-default trap.",
  },
  {
    q: "What does calling a function stored in a dict of handlers, handlers['add'](2,3), require?",
    options: [
      "Nothing works",
      "That handlers['add'] is a function object, then it's called with (2,3)",
      "That add is a string",
      "A decorator",
    ],
    answer: 1,
    explain: "Because functions are first-class, you can store them in a dict and call the retrieved object directly.",
  },
  {
    q: "What does sorted(words, key=str.lower) do?",
    options: [
      "Sorts case-sensitively",
      "Sorts case-insensitively by using the lowercased form as the key",
      "Lowercases the words permanently",
      "Errors",
    ],
    answer: 1,
    explain: "Passing str.lower as the key sorts by the lowercased value, giving case-insensitive ordering without altering the words.",
  },
  {
    q: "What does a lambda with no arguments look like?",
    options: ["lambda: 42", "lambda() 42", "lambda -> 42", "lambda = 42"],
    answer: 0,
    explain: "`lambda: 42` is a zero-argument anonymous function returning 42.",
  },
  {
    q: "Why can't a lambda contain statements like assignments or loops?",
    options: [
      "It can",
      "A lambda's body must be a single expression",
      "Lambdas are deprecated",
      "It needs a decorator",
    ],
    answer: 1,
    explain: "Lambdas are limited to one expression; for multiple statements you need a def.",
  },
  {
    q: "What does this print?  def make_counter():\\n    c = 0\\n    def inc():\\n        nonlocal c\\n        c += 1\\n        return c\\n    return inc\\nf = make_counter()\\nprint(f(), f())",
    options: ["1 1", "1 2", "0 1", "Error"],
    answer: 1,
    explain: "The closure keeps state in c via nonlocal; successive calls return 1 then 2.",
  },
  {
    q: "What does functools.lru_cache do when used as a decorator?",
    options: [
      "Logs calls",
      "Caches results of previous calls to avoid recomputation",
      "Limits recursion depth",
      "Times the function",
    ],
    answer: 1,
    explain: "@lru_cache memoizes results by arguments, so repeated calls with the same inputs return instantly.",
  },
  {
    q: "What does the docstring convention recommend for a function?",
    options: [
      "No documentation",
      "A triple-quoted string as the first statement describing what it does",
      "A # comment only",
      "A print statement",
    ],
    answer: 1,
    explain: "The first statement should be a triple-quoted docstring summarizing purpose, parameters, and return value.",
  },
  {
    q: "What does f.__name__ return for def greet(): ...?",
    options: ["'greet'", "'f'", "None", "The source code"],
    answer: 0,
    explain: "Every function has a __name__ attribute holding its defined name — 'greet' here.",
  },
  {
    q: "What does passing a function to another function enable, e.g. apply(f, x)?",
    options: [
      "Nothing useful",
      "Callback/strategy patterns — the receiver decides when/how to call f",
      "Automatic recursion",
      "Type checking",
    ],
    answer: 1,
    explain: "Passing functions lets the callee invoke your logic (callbacks, strategies, event handlers) — a core benefit of first-class functions.",
  },
  {
    q: "What does this return?  add = lambda x, y=1: x + y\\nadd(5)",
    options: ["6", "5", "51", "Error"],
    answer: 0,
    explain: "Lambdas can have default parameters; add(5) uses y=1, returning 6.",
  },
  {
    q: "What is the scope lookup order Python uses (LEGB)?",
    options: [
      "Global, External, Local, Builtin",
      "Local, Enclosing, Global, Built-in",
      "Local, External, Global, Builtin",
      "Left, Enclosing, Global, Base",
    ],
    answer: 1,
    explain: "Name resolution follows LEGB: Local, then Enclosing functions, then Global (module), then Built-in.",
  },
  {
    q: "What does a function return if it only prints but has no return?",
    options: ["The printed text", "None", "0", "An empty string"],
    answer: 1,
    explain: "print() displays output but the function still returns None since there's no return statement.",
  },
  {
    q: "What does the * do in def f(a, b, *, key)?",
    options: [
      "Collects extra args",
      "Marks everything after it as keyword-only",
      "Multiplies a and b",
      "Nothing",
    ],
    answer: 1,
    explain: "A bare * with no name means subsequent parameters (key) are keyword-only.",
  },
  {
    q: "What does this compute?  def power(base, exp=2): return base ** exp\\npower(3)",
    options: ["9", "6", "3", "8"],
    answer: 0,
    explain: "exp defaults to 2, so power(3) returns 3 ** 2 = 9.",
  },
  {
    q: "What is memoization?",
    options: [
      "Writing notes in code",
      "Caching a function's results so repeated calls with the same inputs are fast",
      "A loop optimization",
      "A type of recursion error",
    ],
    answer: 1,
    explain: "Memoization stores previously computed results keyed by inputs, trading memory for speed on repeated calls.",
  },
  {
    q: "What does calling f() before f is defined (earlier in the file) cause?",
    options: [
      "Works fine",
      "NameError, because the name isn't bound yet at call time",
      "A warning",
      "It returns None",
    ],
    answer: 1,
    explain: "Names must exist when the call executes; calling before the def runs raises NameError.",
  },
  {
    q: "What does def f(items): items.append(1) do to a list passed in?",
    options: [
      "Nothing — lists are copied",
      "Mutates the caller's list, because lists are passed by object reference",
      "Raises an error",
      "Creates a new list",
    ],
    answer: 1,
    explain: "Mutable objects are passed by reference to the same object, so appending inside the function affects the caller's list.",
  },
  {
    q: "What is the benefit of default arguments?",
    options: [
      "They make functions run faster",
      "They let callers omit common values, simplifying calls",
      "They enforce types",
      "They prevent recursion",
    ],
    answer: 1,
    explain: "Defaults provide sensible fallbacks so callers only specify what differs, keeping call sites concise.",
  }
);
