// ── Chapter 07 — File I/O ───────────────────────────────────────────────────
QUESTIONS["07"] = [
  {
    q: "Which built-in function opens a file?",
    options: ["file()", "open()", "read()", "load()"],
    answer: 1,
    explain: "open(path, mode) returns a file object. You then read/write and should close it (or use `with`).",
  },
  {
    q: "What is the recommended way to open a file so it closes automatically?",
    options: [
      "open('f.txt') then hope it closes",
      "with open('f.txt') as f:",
      "file.autoclose('f.txt')",
      "open('f.txt', close=True)",
    ],
    answer: 1,
    explain: "The `with` statement (context manager) guarantees the file is closed when the block ends, even if an error occurs.",
  },
  {
    q: "What mode opens a file for reading (the default)?",
    options: ["'r'", "'w'", "'a'", "'x'"],
    answer: 0,
    explain: "'r' opens for reading and is the default mode. The file must already exist.",
  },
  {
    q: "What does mode 'w' do?",
    options: [
      "Appends to the end",
      "Opens for writing, truncating (erasing) any existing content",
      "Reads only",
      "Fails if the file exists",
    ],
    answer: 1,
    explain: "'w' opens for writing and truncates the file to empty first, or creates it if missing. Existing content is lost.",
  },
  {
    q: "What does mode 'a' do?",
    options: [
      "Overwrites the file",
      "Appends new data to the end, keeping existing content",
      "Reads the file",
      "Raises an error if the file exists",
    ],
    answer: 1,
    explain: "'a' opens for appending: writes go to the end and existing content is preserved. The file is created if missing.",
  },
  {
    q: "What does f.read() return?",
    options: [
      "The first line",
      "The entire remaining file contents as one string",
      "A list of lines",
      "The number of bytes",
    ],
    answer: 1,
    explain: "f.read() reads and returns the whole remaining content as a single string.",
  },
  {
    q: "What does f.readlines() return?",
    options: [
      "One big string",
      "A list of lines (each including its newline)",
      "The first line only",
      "An integer count",
    ],
    answer: 1,
    explain: "f.readlines() returns a list where each element is a line from the file, including trailing '\\n' characters.",
  },
  {
    q: "What is the most memory-efficient way to process a large file line by line?",
    options: [
      "f.read() then split",
      "for line in f:",
      "f.readlines() then loop",
      "Load it into a list first",
    ],
    answer: 1,
    explain: "Iterating the file object directly (`for line in f:`) reads one line at a time, so it scales to huge files without loading everything into memory.",
  },
  {
    q: "Which module reads and writes CSV files in the standard library?",
    options: ["csvfile", "csv", "comma", "tablib"],
    answer: 1,
    explain: "The built-in `csv` module provides reader/writer and DictReader/DictWriter for delimited files.",
  },
  {
    q: "What does csv.DictReader give you for each row?",
    options: [
      "A list of values",
      "A dictionary mapping header names to values",
      "A single string",
      "A tuple of ints",
    ],
    answer: 1,
    explain: "DictReader uses the header row as keys, yielding an ordered dict per row so you access fields by column name.",
  },
  {
    q: "Which module reads and writes JSON in the standard library?",
    options: ["json", "jsonlib", "pyjson", "simplejson (built-in)"],
    answer: 0,
    explain: "The built-in `json` module handles serialization (dump/dumps) and parsing (load/loads).",
  },
  {
    q: "What does json.load(f) do?",
    options: [
      "Writes a Python object to a file",
      "Reads JSON from a file object and returns a Python object",
      "Reads a JSON string",
      "Validates JSON only",
    ],
    answer: 1,
    explain: "json.load(f) parses JSON from an open file object into Python objects (dicts, lists, etc.). json.loads parses from a string.",
  },
  {
    q: "What does json.dump(obj, f) do?",
    options: [
      "Reads JSON",
      "Serializes a Python object as JSON and writes it to file object f",
      "Prints the object",
      "Returns a JSON string",
    ],
    answer: 1,
    explain: "json.dump writes the JSON serialization of obj to the file f. json.dumps returns it as a string instead.",
  },
  {
    q: "What does the indent argument in json.dump(obj, f, indent=2) control?",
    options: [
      "Compression level",
      "Pretty-printing with the given number of spaces per level",
      "The number of keys",
      "Nothing",
    ],
    answer: 1,
    explain: "indent=2 pretty-prints the JSON with 2-space indentation per nesting level, making it human-readable.",
  },
  {
    q: "What does json.loads('{\"a\": 1}') return?",
    options: ["A string", "{'a': 1} (a dict)", "['a', 1]", "An error"],
    answer: 1,
    explain: "json.loads parses a JSON string into Python objects; a JSON object becomes a dict: {'a': 1}.",
  },
  {
    q: "Which library is commonly used to read/write .xlsx Excel files directly?",
    options: ["openpyxl", "xlrd only", "excelpy", "spreadsheet"],
    answer: 0,
    explain: "openpyxl reads and writes modern .xlsx workbooks. pandas can also read/write Excel (using openpyxl under the hood).",
  },
  {
    q: "How does pandas read an Excel file into a DataFrame?",
    options: ["pd.load_excel()", "pd.read_excel('file.xlsx')", "pd.excel()", "pd.open_excel()"],
    answer: 1,
    explain: "pd.read_excel('file.xlsx') loads a sheet into a DataFrame; pd.to_excel writes one back out.",
  },
  {
    q: "Which library reads and manipulates PDF pages (read, merge, split, rotate)?",
    options: ["pypdf", "pdfmaker", "reader", "pdflib-core"],
    answer: 0,
    explain: "pypdf reads existing PDFs and supports merging, splitting, and rotating pages. reportlab is used to create PDFs from scratch.",
  },
  {
    q: "Which library is typically used to CREATE new PDF documents from scratch?",
    options: ["pypdf", "reportlab", "openpyxl", "csv"],
    answer: 1,
    explain: "reportlab generates new PDFs (drawing text/shapes), while pypdf focuses on manipulating existing PDFs.",
  },
  {
    q: "In the pathlib module, what does Path('data') / 'f.txt' produce?",
    options: [
      "A division error",
      "A Path object 'data/f.txt' (or 'data\\\\f.txt' on Windows)",
      "The string 'dataf.txt'",
      "A list",
    ],
    answer: 1,
    explain: "pathlib overloads `/` to join path segments, producing a Path like data/f.txt with the correct OS separator.",
  },
  {
    q: "What does Path('report.txt').suffix return?",
    options: ["'report'", "'.txt'", "'txt'", "'report.txt'"],
    answer: 1,
    explain: ".suffix returns the file extension including the dot: '.txt'. .stem would return 'report'.",
  },
  {
    q: "What does p.glob('*.py') do for a Path p that is a directory?",
    options: [
      "Deletes .py files",
      "Yields the .py files in that directory",
      "Reads all .py files",
      "Renames .py files",
    ],
    answer: 1,
    explain: "glob('*.py') matches paths in the directory against the pattern, yielding the .py files. rglob searches recursively.",
  },
  {
    q: "How do you read an entire text file with pathlib in one call?",
    options: ["Path('f.txt').read_text()", "Path('f.txt').open_all()", "Path.read('f.txt')", "Path('f.txt').text"],
    answer: 0,
    explain: "Path.read_text() opens, reads, and closes the file, returning its content as a string in a single call.",
  },
  {
    q: "What is a good reason to specify encoding='utf-8' when opening a text file?",
    options: [
      "To compress the file",
      "To read/write text consistently across systems and handle non-ASCII characters",
      "To make it binary",
      "It has no effect",
    ],
    answer: 1,
    explain: "Being explicit about UTF-8 avoids platform-default encoding surprises and correctly handles accents, emoji, and other non-ASCII text.",
  },
  {
    q: "What does f.write('hi') return?",
    options: [
      "None",
      "The number of characters written (2)",
      "'hi'",
      "True",
    ],
    answer: 1,
    explain: "file.write() returns the number of characters (for text mode) written — here 2. It does not add a newline automatically.",
  },
  {
    q: "What is JSONL (JSON Lines)?",
    options: [
      "A single JSON array",
      "A format with one independent JSON object per line",
      "Compressed JSON",
      "An invalid format",
    ],
    answer: 1,
    explain: "JSON Lines stores one JSON value per line, which streams well for logs and large datasets since you can process a record at a time.",
  },
  {
    q: "What happens if you open a non-existent file in 'r' mode?",
    options: [
      "It creates the file",
      "FileNotFoundError is raised",
      "It returns None",
      "It opens in append mode",
    ],
    answer: 1,
    explain: "Reading a missing file raises FileNotFoundError. Modes 'w'/'a'/'x' create the file (with different rules).",
  },
  {
    q: "What does Path('folder').mkdir(exist_ok=True) do?",
    options: [
      "Deletes the folder",
      "Creates the folder, and does not error if it already exists",
      "Always raises if it exists",
      "Lists the folder",
    ],
    answer: 1,
    explain: "mkdir with exist_ok=True creates the directory but silently succeeds if it's already there, avoiding FileExistsError.",
  },
];
