// ── Chapter 06 — Comprehensions & Exceptions ────────────────────────────────
QUESTIONS["06"] = [
  {
    q: "What does [x * 2 for x in range(3)] produce?",
    options: ["[0, 2, 4]", "[2, 4, 6]", "[0, 1, 2]", "[1, 2, 3]"],
    answer: 0,
    explain: "The comprehension doubles each of 0, 1, 2, producing [0, 2, 4].",
  },
  {
    q: "What does [x for x in range(6) if x % 2 == 0] produce?",
    options: ["[0, 2, 4]", "[1, 3, 5]", "[0, 1, 2, 3, 4, 5]", "[2, 4]"],
    answer: 0,
    explain: "The `if` filter keeps only even numbers from 0–5: [0, 2, 4].",
  },
  {
    q: "Which builds a dictionary comprehension?",
    options: [
      "{k: v for k, v in pairs}",
      "[k: v for k, v in pairs]",
      "(k: v for k, v in pairs)",
      "{k, v for k, v in pairs}",
    ],
    answer: 0,
    explain: "Dict comprehensions use braces with a key: value expression: {k: v for k, v in pairs}.",
  },
  {
    q: "What does {x for x in [1, 1, 2, 3]} produce?",
    options: ["{1, 1, 2, 3}", "{1, 2, 3}", "[1, 2, 3]", "(1, 2, 3)"],
    answer: 1,
    explain: "A set comprehension yields unique values, so duplicates collapse: {1, 2, 3}.",
  },
  {
    q: "What is [x if x > 0 else 0 for x in [-1, 2, -3]]?",
    options: ["[0, 2, 0]", "[-1, 2, -3]", "[0, 2]", "[2]"],
    answer: 0,
    explain: "The conditional expression (x if x > 0 else 0) maps negatives to 0 and keeps positives: [0, 2, 0].",
  },
  {
    q: "What does [i*j for i in range(2) for j in range(2)] produce?",
    options: ["[0, 0, 0, 1]", "[0, 1, 0, 1]", "[0, 0, 1, 1]", "[1, 1, 1, 1]"],
    answer: 0,
    explain: "Nested loops: (0*0, 0*1, 1*0, 1*1) = [0, 0, 0, 1]. The left for is the outer loop.",
  },
  {
    q: "What is the main advantage of a list comprehension over an equivalent for-loop?",
    options: [
      "It is always faster and more concise for building a list",
      "It can do things loops cannot",
      "It avoids using memory",
      "It never needs a condition",
    ],
    answer: 0,
    explain: "Comprehensions are a concise, typically faster idiom for building a list from an iterable. (For side effects only, a plain loop is clearer.)",
  },
  {
    q: "Which block handles a runtime error so the program can continue?",
    options: ["try/except", "if/else", "for/else", "with/as"],
    answer: 0,
    explain: "A try/except block runs risky code in try and handles exceptions in except, preventing a crash.",
  },
  {
    q: "What exception does int('abc') raise?",
    options: ["TypeError", "ValueError", "KeyError", "IndexError"],
    answer: 1,
    explain: "int() with a non-numeric string raises ValueError — the type is right (str) but the value can't be parsed.",
  },
  {
    q: "What exception does 10 / 0 raise?",
    options: ["ValueError", "ZeroDivisionError", "ArithmeticWarning", "None"],
    answer: 1,
    explain: "Dividing by zero raises ZeroDivisionError.",
  },
  {
    q: "What exception does [1, 2][5] raise?",
    options: ["KeyError", "IndexError", "ValueError", "TypeError"],
    answer: 1,
    explain: "Accessing an out-of-range list index raises IndexError. (KeyError is for dicts.)",
  },
  {
    q: "What exception does {'a': 1}['b'] raise?",
    options: ["IndexError", "KeyError", "ValueError", "NameError"],
    answer: 1,
    explain: "Looking up a missing dict key raises KeyError. Use .get() to avoid it.",
  },
  {
    q: "When does the else block of a try run?",
    options: [
      "Whenever an exception occurs",
      "Only when the try block completes with no exception",
      "Always",
      "Never",
    ],
    answer: 1,
    explain: "The try/except else runs only if the try block raised no exception — a good place for code that should run on success.",
  },
  {
    q: "When does a finally block run?",
    options: [
      "Only on success",
      "Only on error",
      "Always — whether or not an exception occurred",
      "Never",
    ],
    answer: 2,
    explain: "finally always runs, making it ideal for cleanup (closing files, releasing resources) regardless of success or failure.",
  },
  {
    q: "How do you raise an exception manually?",
    options: ["throw ValueError('bad')", "raise ValueError('bad')", "error ValueError", "raise('bad')"],
    answer: 1,
    explain: "Use the `raise` statement with an exception instance: raise ValueError('bad').",
  },
  {
    q: "How do you catch any exception and bind it to a name?",
    options: [
      "except Exception as e:",
      "except e:",
      "catch (e):",
      "except => e:",
    ],
    answer: 0,
    explain: "`except Exception as e:` catches most exceptions and binds the object to e so you can inspect it.",
  },
  {
    q: "What does catching a specific exception type instead of a bare except give you?",
    options: [
      "It runs faster",
      "It handles only the errors you expect and avoids hiding unrelated bugs",
      "It catches syntax errors",
      "Nothing different",
    ],
    answer: 1,
    explain: "Catching specific exceptions keeps unexpected errors from being silently swallowed, which makes debugging far easier.",
  },
  {
    q: "How do you define a custom exception class?",
    options: [
      "class MyError(Exception): pass",
      "def MyError(Exception):",
      "exception MyError:",
      "raise class MyError",
    ],
    answer: 0,
    explain: "Subclass Exception (or a more specific built-in): class MyError(Exception): pass. Then raise MyError('...').",
  },
  {
    q: "Can a single try have multiple except clauses?",
    options: [
      "No, only one",
      "Yes; each handles a different exception type",
      "Only with finally",
      "Only inside a loop",
    ],
    answer: 1,
    explain: "You can chain multiple except clauses, each targeting a different exception type; the first matching one runs.",
  },
  {
    q: "What does 'except (ValueError, TypeError):' do?",
    options: [
      "Catches only ValueError",
      "Catches either ValueError or TypeError",
      "It's a syntax error",
      "Catches all exceptions",
    ],
    answer: 1,
    explain: "A tuple of exception types in one except clause handles any of the listed exceptions.",
  },
  {
    q: "What is the base class of most built-in exceptions?",
    options: ["BaseError", "Exception", "Error", "RuntimeBase"],
    answer: 1,
    explain: "Most catchable exceptions derive from Exception. (BaseException is the true root, but you usually catch Exception.)",
  },
  {
    q: "What does a bare `raise` (with no argument) inside an except block do?",
    options: [
      "Ignores the error",
      "Re-raises the exception currently being handled",
      "Raises a new generic error",
      "Ends the program cleanly",
    ],
    answer: 1,
    explain: "A bare raise inside except re-raises the current exception, letting it propagate after you've done partial handling/logging.",
  },
  {
    q: "What does {k: v for k, v in [('a', 1), ('b', 2)]} produce?",
    options: ["{'a': 1, 'b': 2}", "[('a', 1), ('b', 2)]", "{'a', 'b'}", "{1, 2}"],
    answer: 0,
    explain: "The dict comprehension turns each (key, value) pair into an entry: {'a': 1, 'b': 2}.",
  },
  {
    q: "What is a generator expression, e.g. (x*x for x in range(3))?",
    options: [
      "A list",
      "A lazy iterator that yields values on demand",
      "A tuple",
      "A set",
    ],
    answer: 1,
    explain: "Parentheses create a generator expression — a lazy iterator producing values one at a time, saving memory versus building a full list.",
  },
  {
    q: "What does {c: ord(c) for c in 'ab'} produce?",
    options: ["{'a': 97, 'b': 98}", "{97: 'a', 98: 'b'}", "['a', 'b']", "{97, 98}"],
    answer: 0,
    explain: "The comprehension maps each character to its code point: {'a': 97, 'b': 98}.",
  },
  {
    q: "Why prefer try/except over checking conditions first in some cases (EAFP)?",
    options: [
      "It's the only way",
      "'Easier to Ask Forgiveness than Permission' — attempt the action and handle failure, which is often cleaner and avoids races",
      "It runs without the interpreter",
      "It disables errors globally",
    ],
    answer: 1,
    explain: "Python favors EAFP: try the operation and catch the exception if it fails, rather than pre-checking every condition (LBYL). It's often cleaner and avoids time-of-check/time-of-use races.",
  },
];
