// ── Chapter 03 — Control Flow ───────────────────────────────────────────────
QUESTIONS["03"] = [
  {
    q: "Which keyword begins an alternative condition after an if?",
    options: ["elseif", "elif", "else if", "elsif"],
    answer: 1,
    explain: "Python uses `elif` for chained conditions. `else if` (two words) is not valid Python.",
  },
  {
    q: "What punctuation must follow the condition in an if statement?",
    options: ["A semicolon ;", "A colon :", "A comma ,", "Nothing"],
    answer: 1,
    explain: "Compound statements like if/for/while/def end their header line with a colon, and the body is indented on the following lines.",
  },
  {
    q: "What does this print?  x = 7\\nif x > 5:\\n    print('big')\\nelse:\\n    print('small')",
    options: ["big", "small", "7", "Nothing"],
    answer: 0,
    explain: "7 > 5 is True, so the if-branch runs and prints 'big'.",
  },
  {
    q: "What is the ternary (conditional) expression form in Python?",
    options: [
      "cond ? a : b",
      "a if cond else b",
      "if cond then a else b",
      "a when cond otherwise b",
    ],
    answer: 1,
    explain: "Python's conditional expression is `a if cond else b`. There is no `?:` operator.",
  },
  {
    q: "What does range(5) generate?",
    options: [
      "1, 2, 3, 4, 5",
      "0, 1, 2, 3, 4",
      "0, 1, 2, 3, 4, 5",
      "5",
    ],
    answer: 1,
    explain: "range(5) yields 0 up to but not including 5: 0, 1, 2, 3, 4.",
  },
  {
    q: "What does range(2, 8, 2) produce?",
    options: ["2, 4, 6", "2, 4, 6, 8", "2, 3, 4, 5, 6, 7", "2, 8"],
    answer: 0,
    explain: "range(start, stop, step) = 2, 4, 6 — it starts at 2, steps by 2, and stops before 8.",
  },
  {
    q: "How many times does this loop run?  for i in range(3):",
    options: ["2", "3", "4", "Infinite"],
    answer: 1,
    explain: "range(3) produces 0, 1, 2 — three values — so the loop body runs 3 times.",
  },
  {
    q: "What does enumerate(['a','b']) yield when iterated?",
    options: [
      "'a', 'b'",
      "(0, 'a'), (1, 'b')",
      "0, 1",
      "('a', 0), ('b', 1)",
    ],
    answer: 1,
    explain: "enumerate() pairs each item with its index: (0, 'a'), (1, 'b'). Great for looping when you need both index and value.",
  },
  {
    q: "What does the break statement do inside a loop?",
    options: [
      "Skips to the next iteration",
      "Immediately exits the innermost loop",
      "Pauses the program",
      "Restarts the loop",
    ],
    answer: 1,
    explain: "break terminates the nearest enclosing loop immediately, jumping to the code after it.",
  },
  {
    q: "What does continue do inside a loop?",
    options: [
      "Exits the loop entirely",
      "Skips the rest of the current iteration and moves to the next",
      "Repeats the current iteration",
      "Ends the program",
    ],
    answer: 1,
    explain: "continue abandons the rest of the current iteration and jumps back to the loop header for the next one.",
  },
  {
    q: "When does a loop's `else` clause execute?",
    options: [
      "Only when the loop body never runs",
      "When the loop finishes normally without hitting break",
      "Every time the loop iterates",
      "Only if break is hit",
    ],
    answer: 1,
    explain: "A loop's else runs if the loop completes without a break. If break fires, the else is skipped.",
  },
  {
    q: "What does zip([1,2],[3,4]) yield when iterated?",
    options: ["(1,2),(3,4)", "(1,3),(2,4)", "1,2,3,4", "[1,3,2,4]"],
    answer: 1,
    explain: "zip pairs items by position across the iterables: (1,3), (2,4). It stops at the shortest input.",
  },
  {
    q: "How do you write an intentional infinite loop?",
    options: ["while True:", "for ever:", "loop:", "while 1 == 2:"],
    answer: 0,
    explain: "`while True:` loops forever until a break (or other exit). You usually pair it with a break condition inside.",
  },
  {
    q: "What is printed?  for i in range(1, 4):\\n    print(i, end=' ')",
    options: ["1 2 3", "0 1 2", "1 2 3 4", "1 2 3 "],
    answer: 3,
    explain: "range(1,4) is 1, 2, 3; with end=' ' each is followed by a space, giving '1 2 3 ' (note the trailing space).",
  },
  {
    q: "What does this compute?  total = 0\\nfor n in [4, 5, 6]:\\n    total += n",
    options: ["15", "456", "3", "[4,5,6]"],
    answer: 0,
    explain: "The loop accumulates 4 + 5 + 6 into total, giving 15.",
  },
  {
    q: "Which loop is best when you don't know the number of iterations in advance?",
    options: ["for loop", "while loop", "range loop", "enumerate loop"],
    answer: 1,
    explain: "A while loop repeats based on a condition, which suits situations where the count isn't known ahead of time (e.g. reading until a sentinel).",
  },
  {
    q: "What happens with a nested loop: for i in range(2): for j in range(3):  — how many inner iterations total?",
    options: ["5", "6", "3", "2"],
    answer: 1,
    explain: "The inner loop (3 iterations) runs fully for each of the 2 outer iterations: 2 × 3 = 6 total.",
  },
  {
    q: "What does the pass statement do?",
    options: [
      "Exits the program",
      "Nothing — it's a placeholder that does nothing",
      "Skips a loop iteration",
      "Raises an error",
    ],
    answer: 1,
    explain: "pass is a no-op placeholder used where a statement is syntactically required but you have nothing to do yet.",
  },
  {
    q: "What is the value of grade?  score = 85\\ngrade = 'A' if score >= 90 else 'B'",
    options: ["'A'", "'B'", "85", "None"],
    answer: 1,
    explain: "85 >= 90 is False, so the else branch is chosen and grade is 'B'.",
  },
  {
    q: "What does this print?  n = 10\\nwhile n > 0:\\n    n -= 3\\nprint(n)",
    options: ["0", "1", "-2", "It loops forever"],
    answer: 2,
    explain: "n goes 10 → 7 → 4 → 1 → -2; once n is -2 the condition n > 0 is False and the loop stops, printing -2.",
  },
  {
    q: "In Python, how do you check if 'x' is in the list letters?",
    options: ["letters.has('x')", "'x' in letters", "letters contains 'x'", "in(letters, 'x')"],
    answer: 1,
    explain: "The `in` membership operator returns True if the value is present: `'x' in letters`.",
  },
  {
    q: "What does this loop print?  for c in 'hi':\\n    print(c)",
    options: ["hi", "h then i (on separate lines)", "0 1", "['h','i']"],
    answer: 1,
    explain: "Iterating a string yields its characters one by one, so it prints 'h' then 'i' on separate lines.",
  },
  {
    q: "Which condition is True when a is between 1 and 10 inclusive?",
    options: ["1 < a < 10", "1 <= a <= 10", "a in 1..10", "a >= 1 or a <= 10"],
    answer: 1,
    explain: "Python supports chained comparisons: `1 <= a <= 10` is True when a is at least 1 and at most 10.",
  },
  {
    q: "What is the output?  for i in range(3):\\n    if i == 1:\\n        continue\\n    print(i)",
    options: ["0 1 2", "0 2", "1", "0 1"],
    answer: 1,
    explain: "When i is 1, continue skips the print, so only 0 and 2 are printed.",
  },
];
