// ── Chapter 08 — Modules & Packages · expansion pool ────────────────────────
QUESTIONS["08"].push(
  {
    q: "What does math.sqrt(16) return?",
    options: ["4.0", "4", "8", "256"],
    answer: 0,
    explain: "math.sqrt returns a float, so sqrt(16) is 4.0.",
  },
  {
    q: "What does math.floor(3.7) return?",
    options: ["4", "3", "3.7", "3.0"],
    answer: 1,
    explain: "math.floor rounds down to the nearest integer: 3. math.ceil(3.2) would give 4.",
  },
  {
    q: "What does math.ceil(3.2) return?",
    options: ["3", "4", "3.2", "4.0"],
    answer: 1,
    explain: "math.ceil rounds up to the nearest integer: 4.",
  },
  {
    q: "What does random.random() return?",
    options: [
      "A random integer",
      "A random float in [0.0, 1.0)",
      "A random letter",
      "0 or 1",
    ],
    answer: 1,
    explain: "random.random() returns a float x where 0.0 <= x < 1.0.",
  },
  {
    q: "What does random.shuffle(lst) do?",
    options: [
      "Returns a shuffled copy",
      "Shuffles the list in place and returns None",
      "Sorts the list",
      "Picks one element",
    ],
    answer: 1,
    explain: "random.shuffle rearranges the list in place and returns None.",
  },
  {
    q: "What does random.sample(range(10), 3) return?",
    options: [
      "3 unique random values from 0-9",
      "A single value",
      "All 10 values",
      "3 possibly repeated values",
    ],
    answer: 0,
    explain: "sample returns a list of k unique elements chosen without replacement — 3 distinct values here.",
  },
  {
    q: "What does datetime.now() give you that date.today() does not?",
    options: [
      "Only the date",
      "The time-of-day component as well",
      "The timezone always",
      "Nothing extra",
    ],
    answer: 1,
    explain: "datetime.now() includes both date and time; date.today() is date-only.",
  },
  {
    q: "What does timedelta(days=7) represent?",
    options: [
      "A specific date",
      "A duration of 7 days you can add to/subtract from a date",
      "The 7th day",
      "A week number",
    ],
    answer: 1,
    explain: "timedelta is a duration; adding it to a date shifts it (e.g. today + timedelta(days=7)).",
  },
  {
    q: "What does strftime do on a datetime?",
    options: [
      "Parses a string into a datetime",
      "Formats a datetime into a string using format codes",
      "Adds time",
      "Returns the timestamp",
    ],
    answer: 1,
    explain: "strftime ('string format time') renders a datetime as text via codes like %Y-%m-%d. strptime parses the reverse.",
  },
  {
    q: "What does collections.deque provide over a list?",
    options: [
      "Sorting",
      "Fast O(1) appends and pops from both ends",
      "Key-value storage",
      "Immutability",
    ],
    answer: 1,
    explain: "deque is a double-ended queue with efficient appendleft/popleft, unlike a list where front operations are O(n).",
  },
  {
    q: "What does collections.namedtuple create?",
    options: [
      "A dict subclass",
      "A tuple subclass with named, accessible fields",
      "A mutable list",
      "A set",
    ],
    answer: 1,
    explain: "namedtuple builds a lightweight immutable class whose fields are accessible by name (p.x) and by index.",
  },
  {
    q: "What does itertools.chain([1,2], [3,4]) yield?",
    options: ["[[1,2],[3,4]]", "1, 2, 3, 4", "[1,3,2,4]", "(1,2,3,4) reversed"],
    answer: 1,
    explain: "chain concatenates iterables, yielding their elements in sequence: 1, 2, 3, 4.",
  },
  {
    q: "What does itertools.combinations('ABC', 2) produce?",
    options: [
      "AB, AC, BC",
      "AB, BA, AC, CA, BC, CB",
      "A, B, C",
      "ABC",
    ],
    answer: 0,
    explain: "combinations gives unordered pairs without repeats: AB, AC, BC. permutations would include order.",
  },
  {
    q: "What does itertools.product([1,2], [3,4]) produce?",
    options: [
      "(1,3),(1,4),(2,3),(2,4)",
      "(1,3),(2,4)",
      "1,2,3,4",
      "(4,6)",
    ],
    answer: 0,
    explain: "product is the Cartesian product (nested-loop equivalent): all pairs (1,3),(1,4),(2,3),(2,4).",
  },
  {
    q: "What does functools.reduce require to import?",
    options: [
      "It's a builtin",
      "from functools import reduce",
      "import reduce",
      "from itertools import reduce",
    ],
    answer: 1,
    explain: "reduce lives in functools (it was removed from builtins in Python 3), so you import it explicitly.",
  },
  {
    q: "What does sys.path represent?",
    options: [
      "The current file path",
      "The list of directories Python searches for imports",
      "Environment variables",
      "The Python version",
    ],
    answer: 1,
    explain: "sys.path is the module search path; Python looks through these directories to resolve imports.",
  },
  {
    q: "What does sys.exit() do?",
    options: [
      "Restarts the program",
      "Terminates the program (raising SystemExit)",
      "Clears memory",
      "Returns None",
    ],
    answer: 1,
    explain: "sys.exit() raises SystemExit to end the program, optionally with a status code or message.",
  },
  {
    q: "What does Python do the second time you import an already-imported module?",
    options: [
      "Re-runs the module code",
      "Uses the cached module from sys.modules (doesn't re-run it)",
      "Raises an error",
      "Creates a copy",
    ],
    answer: 1,
    explain: "Modules are cached in sys.modules after first import, so re-importing reuses the loaded module without re-executing it.",
  },
  {
    q: "What is a circular import?",
    options: [
      "Importing a module twice",
      "Two modules importing each other, which can cause partial/incomplete imports",
      "A round-robin loop",
      "Importing from a package",
    ],
    answer: 1,
    explain: "When module A imports B and B imports A, one may see the other only partially initialized — a common source of ImportError.",
  },
  {
    q: "What does dir(module) return?",
    options: [
      "The module's file path",
      "A list of names (attributes) defined in the module",
      "The docstring",
      "The version",
    ],
    answer: 1,
    explain: "dir() lists the names available in the module (functions, classes, variables), handy for exploring.",
  },
  {
    q: "What does a module's __doc__ attribute hold?",
    options: [
      "Its file size",
      "Its module-level docstring",
      "Its functions",
      "Its imports",
    ],
    answer: 1,
    explain: "__doc__ is the module's docstring — the triple-quoted string at the top of the file.",
  },
  {
    q: "What does the statistics module's mean([1,2,3,4]) return?",
    options: ["2.5", "10", "4", "2"],
    answer: 0,
    explain: "statistics.mean computes the average: (1+2+3+4)/4 = 2.5.",
  },
  {
    q: "What does statistics.median([1, 3, 5, 7]) return?",
    options: ["3", "4.0", "5", "16"],
    answer: 1,
    explain: "With an even count, the median is the average of the two middle values (3 and 5): 4.0.",
  },
  {
    q: "What does the string module's string.ascii_lowercase contain?",
    options: [
      "'ABC...Z'",
      "'abcdefghijklmnopqrstuvwxyz'",
      "Digits",
      "Punctuation",
    ],
    answer: 1,
    explain: "string.ascii_lowercase is the constant 'abcdefghijklmnopqrstuvwxyz'.",
  },
  {
    q: "What does the secrets module provide over random?",
    options: [
      "Faster numbers",
      "Cryptographically strong randomness for tokens/passwords",
      "Sorted output",
      "Nothing different",
    ],
    answer: 1,
    explain: "secrets generates cryptographically secure random values, appropriate for security-sensitive tokens (unlike random).",
  },
  {
    q: "What does uuid.uuid4() generate?",
    options: [
      "A sequential ID",
      "A random universally unique identifier",
      "A hash of the input",
      "A timestamp",
    ],
    answer: 1,
    explain: "uuid4() produces a random 128-bit UUID, useful for unique keys/filenames.",
  },
  {
    q: "What is argparse used for?",
    options: [
      "Parsing JSON",
      "Building command-line interfaces that parse sys.argv into typed options",
      "Parsing dates",
      "Reading files",
    ],
    answer: 1,
    explain: "argparse defines and parses command-line arguments, generating help text and validation automatically.",
  },
  {
    q: "What does the logging module offer over print for diagnostics?",
    options: [
      "Nothing",
      "Levels, timestamps, configurable outputs, and the ability to silence/redirect messages",
      "Colored text only",
      "Faster output",
    ],
    answer: 1,
    explain: "logging supports severity levels (DEBUG..CRITICAL), formatting, and routing to files/handlers — far more flexible than print.",
  },
  {
    q: "What does pprint.pprint do?",
    options: [
      "Prints faster",
      "Pretty-prints nested data structures readably",
      "Prints to a file",
      "Prints in color",
    ],
    answer: 1,
    explain: "pprint formats complex/nested structures (dicts, lists) with indentation for readability.",
  },
  {
    q: "What is the difference between a module and a package?",
    options: [
      "None",
      "A module is a single .py file; a package is a directory of modules (with __init__.py)",
      "A package is smaller",
      "A module can't be imported",
    ],
    answer: 1,
    explain: "A module is one file; a package groups related modules in a directory, traditionally marked by __init__.py.",
  },
  {
    q: "What does 'from package import module' do?",
    options: [
      "Imports a function",
      "Imports the submodule 'module' from 'package'",
      "Runs the package",
      "Errors",
    ],
    answer: 1,
    explain: "It imports the named submodule from the package so you can use package.module's contents.",
  },
  {
    q: "What does the __file__ attribute of a module contain?",
    options: [
      "Its source code",
      "The path to the module's file",
      "Its size",
      "Its docstring",
    ],
    answer: 1,
    explain: "__file__ holds the filesystem path of the loaded module.",
  },
  {
    q: "What does 'import module as m' primarily help with?",
    options: [
      "Speed",
      "Giving a long module name a short, convenient alias",
      "Security",
      "Avoiding execution",
    ],
    answer: 1,
    explain: "Aliasing shortens references (e.g. import numpy as np), reducing typing and following community conventions.",
  },
  {
    q: "What does os.getcwd() return?",
    options: [
      "The user's home directory",
      "The current working directory",
      "The script's directory",
      "The Python install path",
    ],
    answer: 1,
    explain: "os.getcwd() returns the process's current working directory.",
  },
  {
    q: "What does os.listdir('.') return?",
    options: [
      "Recursive files",
      "A list of entries in the current directory",
      "Only files",
      "The directory size",
    ],
    answer: 1,
    explain: "os.listdir returns the names of entries (files and subdirs) in the given directory.",
  },
  {
    q: "What does os.environ.get('HOME') do?",
    options: [
      "Sets HOME",
      "Reads the HOME environment variable (or None if unset)",
      "Deletes HOME",
      "Lists all variables",
    ],
    answer: 1,
    explain: "os.environ is a mapping of environment variables; .get returns the value or None if it's not defined.",
  },
  {
    q: "What does the time.time() function return?",
    options: [
      "A formatted date",
      "The current time as seconds since the epoch (a float)",
      "The CPU time",
      "A timezone",
    ],
    answer: 1,
    explain: "time.time() returns Unix epoch seconds as a float, commonly used for timing durations.",
  },
  {
    q: "What does defaultdict(list) do on d['new'].append(1) for a missing key?",
    options: [
      "Raises KeyError",
      "Auto-creates an empty list for 'new', then appends 1",
      "Ignores it",
      "Creates a set",
    ],
    answer: 1,
    explain: "defaultdict(list) supplies a fresh [] for missing keys, so you can append without a pre-check.",
  },
  {
    q: "What does Counter's .most_common(2) return?",
    options: [
      "The two rarest items",
      "The two most frequent (element, count) pairs",
      "Two random items",
      "All items",
    ],
    answer: 1,
    explain: "most_common(n) returns the n highest-count pairs, ordered from most to least frequent.",
  },
  {
    q: "What does itertools.count(10) do?",
    options: [
      "Counts to 10",
      "Yields an infinite sequence 10, 11, 12, ...",
      "Returns 10",
      "Repeats 10 times",
    ],
    answer: 1,
    explain: "count(start) is an infinite iterator producing consecutive numbers from start; pair it with a break or islice.",
  },
  {
    q: "What does itertools.cycle('AB') do?",
    options: [
      "Yields A, B once",
      "Yields A, B, A, B, ... indefinitely",
      "Sorts the string",
      "Returns 'AB'",
    ],
    answer: 1,
    explain: "cycle repeats the iterable forever: A, B, A, B, ...",
  },
  {
    q: "What is the entry-point idiom that keeps a module importable and runnable?",
    options: [
      "Putting everything at top level",
      "def main(): ... then `if __name__ == '__main__': main()`",
      "Using only lambdas",
      "A while loop",
    ],
    answer: 1,
    explain: "Wrapping the script logic in main() and guarding its call with the __name__ check avoids running it on import.",
  },
  {
    q: "What happens to top-level code in a module when you import it?",
    options: [
      "It's skipped",
      "It runs once at import time",
      "It never runs",
      "It runs on every access",
    ],
    answer: 1,
    explain: "Importing a module executes its top-level statements once; that's why heavy work belongs under the __main__ guard.",
  },
  {
    q: "What does 'import a.b.c' make available?",
    options: [
      "Only c",
      "The full dotted path a.b.c (you use a.b.c.something)",
      "b only",
      "Nothing",
    ],
    answer: 1,
    explain: "It imports the nested module, accessible via the full path a.b.c.",
  },
  {
    q: "What does the __pycache__ directory store per module?",
    options: [
      "Source code",
      "Compiled bytecode (.pyc) tagged with the Python version",
      "Documentation",
      "Test results",
    ],
    answer: 1,
    explain: "Compiled bytecode is cached in __pycache__ as version-tagged .pyc files to speed up subsequent imports.",
  },
  {
    q: "What does importlib.reload(module) do?",
    options: [
      "Deletes the module",
      "Re-executes and updates an already-imported module",
      "Imports it for the first time",
      "Lists its contents",
    ],
    answer: 1,
    explain: "reload re-runs the module's code and updates the existing module object, useful in interactive sessions after edits.",
  },
  {
    q: "What does the 'as' in 'from math import pi as PI' do?",
    options: [
      "Errors",
      "Imports pi under the local name PI",
      "Imports all of math",
      "Renames math",
    ],
    answer: 1,
    explain: "It binds the imported name to a local alias, so you refer to it as PI.",
  },
  {
    q: "Why guard expensive setup with `if __name__ == '__main__'`?",
    options: [
      "For speed only",
      "So it runs when executed directly but not when the module is imported elsewhere",
      "To hide the code",
      "It's required syntax",
    ],
    answer: 1,
    explain: "The guard prevents script-only side effects from firing when another file merely imports the module.",
  }
);
