// ── Chapter 03 — Control Flow · expansion pool ──────────────────────────────
QUESTIONS["03"].push(
  {
    q: "What does this print?  x = 0\\nif x:\\n    print('a')\\nelse:\\n    print('b')",
    options: ["a", "b", "0", "Nothing"],
    answer: 1,
    explain: "0 is falsy, so the else branch runs, printing 'b'.",
  },
  {
    q: "How many branches can run in a single if/elif/elif/else chain?",
    options: ["All of them", "Exactly one", "At most two", "None"],
    answer: 1,
    explain: "Python evaluates conditions top-down and runs only the first branch whose condition is True (or else); exactly one branch executes.",
  },
  {
    q: "What does range(10, 0, -2) produce?",
    options: ["10, 8, 6, 4, 2", "10, 8, 6, 4, 2, 0", "0, 2, 4, 6, 8, 10", "10 down to 1"],
    answer: 0,
    explain: "Starting at 10, stepping -2, stopping before 0: 10, 8, 6, 4, 2.",
  },
  {
    q: "What does len(range(0, 10, 3)) return?",
    options: ["3", "4", "10", "9"],
    answer: 1,
    explain: "range(0,10,3) is 0, 3, 6, 9 — four values.",
  },
  {
    q: "What does list(enumerate('ab', start=1)) return?",
    options: ["[(1,'a'), (2,'b')]", "[(0,'a'), (1,'b')]", "['a','b']", "[(1,2)]"],
    answer: 0,
    explain: "enumerate's start parameter sets the first index; here counting begins at 1: [(1,'a'), (2,'b')].",
  },
  {
    q: "What does this compute?  s = 0\\nfor i in range(1, 6):\\n    s += i",
    options: ["10", "15", "6", "21"],
    answer: 1,
    explain: "It sums 1+2+3+4+5 = 15.",
  },
  {
    q: "What does this print?  for i in range(3):\\n    for j in range(2):\\n        print(i, j)  # count lines",
    options: ["3 lines", "5 lines", "6 lines", "2 lines"],
    answer: 2,
    explain: "The inner loop runs 2 times for each of the 3 outer iterations: 3 × 2 = 6 lines.",
  },
  {
    q: "What does the break in this loop cause?  for n in [1,2,3,4]:\\n    if n == 3:\\n        break\\n    print(n)",
    options: ["Prints 1 2", "Prints 1 2 3", "Prints 3 4", "Prints nothing"],
    answer: 0,
    explain: "It prints 1 and 2, then hits break when n == 3 and exits before printing 3.",
  },
  {
    q: "What does this print?  for n in [1,2,3,4]:\\n    if n % 2 == 0:\\n        continue\\n    print(n)",
    options: ["1 3", "2 4", "1 2 3 4", "Nothing"],
    answer: 0,
    explain: "continue skips even numbers, so only the odd values 1 and 3 are printed.",
  },
  {
    q: "In a for/else, when does the else run?",
    options: [
      "When the loop body errors",
      "When the loop completes without hitting break",
      "Every iteration",
      "Never with a for loop",
    ],
    answer: 1,
    explain: "The else after a for/while runs only if the loop finished normally (no break) — often used in search loops.",
  },
  {
    q: "What does this print?  for n in [2,4,6]:\\n    if n == 5:\\n        break\\nelse:\\n    print('no 5')",
    options: ["Nothing", "'no 5'", "5", "Error"],
    answer: 1,
    explain: "No element equals 5, so break never fires and the loop's else runs, printing 'no 5'.",
  },
  {
    q: "What does while with no reachable exit (e.g. while True with no break) cause?",
    options: ["A syntax error", "An infinite loop", "It runs once", "It runs zero times"],
    answer: 1,
    explain: "Without a break or a condition that becomes False, `while True` loops forever.",
  },
  {
    q: "What does this leave in count?  count = 0\\nwhile count < 5:\\n    count += 1",
    options: ["4", "5", "6", "0"],
    answer: 1,
    explain: "count increments until it reaches 5, at which point 5 < 5 is False and the loop stops; count is 5.",
  },
  {
    q: "What is the result of the chained comparison 5 == 5 == 5?",
    options: ["True", "False", "25", "Error"],
    answer: 0,
    explain: "Chained comparison means 5 == 5 and 5 == 5, both True, so the whole expression is True.",
  },
  {
    q: "What does 'not (3 > 2)' evaluate to?",
    options: ["True", "False", "3", "Error"],
    answer: 1,
    explain: "3 > 2 is True; `not True` is False.",
  },
  {
    q: "Which value makes this condition True?  if x and not y",
    options: ["x truthy, y truthy", "x truthy, y falsy", "x falsy, y falsy", "x falsy, y truthy"],
    answer: 1,
    explain: "The expression needs x truthy AND y falsy (so `not y` is True).",
  },
  {
    q: "What does this print?  n = 7\\nprint('even' if n % 2 == 0 else 'odd')",
    options: ["even", "odd", "7", "Nothing"],
    answer: 1,
    explain: "7 % 2 is 1 (not 0), so the ternary chooses 'odd'.",
  },
  {
    q: "How do you loop over a list in reverse order?",
    options: ["for x in reverse(lst):", "for x in reversed(lst):", "for x in lst.reverse():", "for x in lst[::0]:"],
    answer: 1,
    explain: "reversed(lst) yields the items back-to-front. (lst.reverse() reverses in place and returns None.)",
  },
  {
    q: "What does this print?  for i, c in enumerate('hi'):\\n    print(i, c)  # first line",
    options: ["0 h", "1 h", "h 0", "0 hi"],
    answer: 0,
    explain: "enumerate pairs index with value; the first line is '0 h'.",
  },
  {
    q: "What does zip(['a','b','c'], [1,2]) produce when listed?",
    options: [
      "[('a',1),('b',2),('c',None)]",
      "[('a',1),('b',2)]",
      "[('a',1),('b',2),('c',3)]",
      "Error",
    ],
    answer: 1,
    explain: "zip stops at the shortest iterable, so 'c' has no pair: [('a',1),('b',2)].",
  },
  {
    q: "What does the match statement (Python 3.10+) do?",
    options: [
      "Regex matching only",
      "Structural pattern matching — compares a value against patterns (case clauses)",
      "String equality only",
      "Nothing new",
    ],
    answer: 1,
    explain: "match/case performs structural pattern matching, dispatching on the shape/value of a subject — a richer alternative to long if/elif chains.",
  },
  {
    q: "In match/case, what does the pattern `case _:` mean?",
    options: [
      "Match nothing",
      "The wildcard/default that matches anything",
      "Match an underscore literal",
      "A syntax error",
    ],
    answer: 1,
    explain: "`case _:` is the wildcard pattern — it matches any value, serving as the default branch.",
  },
  {
    q: "What does this print?  total = 0\\nfor row in [[1,2],[3,4]]:\\n    for v in row:\\n        total += v",
    options: ["10", "1234", "7", "[1,2,3,4]"],
    answer: 0,
    explain: "Nested loops sum all elements: 1+2+3+4 = 10.",
  },
  {
    q: "What does `if 'a' in 'cat':` evaluate?",
    options: [
      "Whether 'a' is an index",
      "Whether the substring 'a' occurs in 'cat' (True)",
      "Whether 'a' equals 'cat'",
      "Nothing valid",
    ],
    answer: 1,
    explain: "`in` on strings tests substring membership; 'a' is in 'cat', so the condition is True.",
  },
  {
    q: "What does `for _ in range(3):` convey by using _ as the variable?",
    options: [
      "An error",
      "That the loop variable is intentionally unused",
      "That it loops backwards",
      "That it's a private loop",
    ],
    answer: 1,
    explain: "By convention _ signals 'I don't need this value' — here just repeating the body 3 times.",
  },
  {
    q: "What does this print?  x = 5\\nif x > 0:\\n    if x > 10:\\n        print('big')\\n    else:\\n        print('small')",
    options: ["big", "small", "Nothing", "Error"],
    answer: 1,
    explain: "x > 0 is True, then x > 10 is False, so the inner else runs, printing 'small'.",
  },
  {
    q: "What does sum(range(1, 101)) compute?",
    options: ["5000", "5050", "100", "10000"],
    answer: 1,
    explain: "The sum of 1 through 100 is 5050 (n(n+1)/2 with n=100). sum() over the range gives this directly.",
  },
  {
    q: "What does this print?  i = 0\\nwhile i < 3:\\n    print(i)\\n    i += 1  # last value printed",
    options: ["2", "3", "0", "Infinite"],
    answer: 0,
    explain: "It prints 0, 1, 2; when i becomes 3 the condition fails. The last printed value is 2.",
  },
  {
    q: "Which is the correct way to iterate a dict's keys and values together?",
    options: [
      "for k, v in d:",
      "for k, v in d.items():",
      "for k in d.values():",
      "for k, v in d.keys():",
    ],
    answer: 1,
    explain: "d.items() yields (key, value) pairs, which unpack into k, v each iteration.",
  },
  {
    q: "What does `range(5)[::-1]` effectively iterate as when listed?",
    options: ["[4,3,2,1,0]", "[0,1,2,3,4]", "[5,4,3,2,1]", "Error"],
    answer: 0,
    explain: "Slicing the range with step -1 reverses it: [4, 3, 2, 1, 0].",
  },
  {
    q: "What does the condition `if not items:` typically check?",
    options: [
      "Whether items is True",
      "Whether the container items is empty",
      "Whether items has been deleted",
      "Whether items is a number",
    ],
    answer: 1,
    explain: "Empty containers are falsy, so `not items` is True when items is empty — the idiomatic emptiness check.",
  },
  {
    q: "What does this print?  print('big' if 10 > 5 > 1 else 'no')",
    options: ["big", "no", "True", "Error"],
    answer: 0,
    explain: "10 > 5 > 1 is a chained comparison (10>5 and 5>1), both True, so it prints 'big'.",
  },
  {
    q: "What is a guard clause?",
    options: [
      "A security feature",
      "An early return/continue that handles an edge case first to reduce nesting",
      "A type of loop",
      "A comment",
    ],
    answer: 1,
    explain: "A guard clause checks an edge condition up front and exits early (return/continue/break), keeping the main logic un-nested.",
  },
  {
    q: "What does this loop build?  out = []\\nfor x in range(4):\\n    if x % 2:\\n        out.append(x)",
    options: ["[0, 2]", "[1, 3]", "[0,1,2,3]", "[]"],
    answer: 1,
    explain: "x % 2 is truthy for odd numbers, so out collects the odd values: [1, 3].",
  },
  {
    q: "What does `while data:` do when data is a list being emptied inside the loop?",
    options: [
      "Loops forever",
      "Loops while the list is non-empty (truthy) and stops when empty",
      "Errors",
      "Runs exactly once",
    ],
    answer: 1,
    explain: "A non-empty list is truthy; as the loop removes items, once the list is empty it becomes falsy and the loop ends.",
  },
  {
    q: "What is printed?  for i in range(2):\\n    for j in range(2):\\n        if j == 1:\\n            break\\n        print(i, j)",
    options: ["0 0 and 1 0", "0 0 only", "0 0, 0 1, 1 0, 1 1", "Nothing"],
    answer: 0,
    explain: "The inner break only exits the inner loop, so each outer iteration prints once: '0 0' then '1 0'.",
  },
  {
    q: "What does any([False, 0, '', 3]) return?",
    options: ["True", "False", "3", "Error"],
    answer: 0,
    explain: "any() is True if at least one element is truthy; 3 is truthy, so it returns True.",
  },
  {
    q: "What does all([1, 2, 0, 3]) return?",
    options: ["True", "False", "0", "6"],
    answer: 1,
    explain: "all() is True only if every element is truthy; 0 is falsy, so it returns False.",
  },
  {
    q: "What does min([4, 2, 8, 1]) return?",
    options: ["1", "8", "4", "2"],
    answer: 0,
    explain: "min() returns the smallest element: 1.",
  },
  {
    q: "What does max('apple', 'pear', 'fig', key=len) return?",
    options: ["'apple'", "'pear'", "'fig'", "'p'"],
    answer: 0,
    explain: "With key=len, max compares by length; 'apple' (5) is longest.",
  },
  {
    q: "What does this compute?  count = 0\\nfor c in 'hello':\\n    if c == 'l':\\n        count += 1",
    options: ["1", "2", "3", "0"],
    answer: 1,
    explain: "There are two 'l' characters in 'hello', so count becomes 2.",
  },
  {
    q: "What does the expression `x = 5 if cond else 10 if cond2 else 0` do?",
    options: [
      "Errors",
      "Chains ternaries: 5 if cond, else (10 if cond2 else 0)",
      "Always assigns 5",
      "Assigns a tuple",
    ],
    answer: 1,
    explain: "Conditional expressions can nest; it reads as 5 if cond else (10 if cond2 else 0).",
  },
  {
    q: "What does `for line in open('f.txt'):` iterate over?",
    options: ["Characters", "Lines of the file", "Words", "Bytes"],
    answer: 1,
    explain: "Iterating a text file object yields one line per iteration.",
  },
  {
    q: "What does this print?  n = 4\\nresult = 'positive' if n > 0 else 'non-positive'\\nprint(result)",
    options: ["positive", "non-positive", "4", "True"],
    answer: 0,
    explain: "n > 0 is True, so result is 'positive'.",
  },
  {
    q: "Which loop form is idiomatic for repeating something a fixed number of times?",
    options: ["while with a counter", "for _ in range(n):", "recursion", "goto"],
    answer: 1,
    explain: "`for _ in range(n):` is the clear, idiomatic way to repeat a block n times.",
  },
  {
    q: "What does `if a == b == c:` require to be True?",
    options: [
      "Only a == b",
      "a equals b AND b equals c",
      "a equals c only",
      "At least one pair equal",
    ],
    answer: 1,
    explain: "Chained comparison a == b == c means (a == b) and (b == c) — all three must be equal.",
  },
  {
    q: "What does this build?  pairs = []\\nfor i in range(2):\\n    for j in range(2):\\n        pairs.append((i, j))",
    options: [
      "[(0,0),(0,1),(1,0),(1,1)]",
      "[(0,0),(1,1)]",
      "[(0,1),(1,0)]",
      "[]",
    ],
    answer: 0,
    explain: "Nested loops enumerate all combinations: (0,0), (0,1), (1,0), (1,1).",
  },
  {
    q: "What happens if the body of a for loop is empty but you write `pass`?",
    options: [
      "Error",
      "The loop iterates doing nothing each time",
      "The loop is skipped",
      "It prints pass",
    ],
    answer: 1,
    explain: "`pass` is a no-op placeholder; the loop still iterates, just with no work per iteration.",
  },
  {
    q: "What does sorted([3,1,2], reverse=True) return?",
    options: ["[1,2,3]", "[3,2,1]", "[2,1,3]", "None"],
    answer: 1,
    explain: "sorted() with reverse=True returns a new list in descending order: [3, 2, 1].",
  },
  {
    q: "What does the condition `if score >= 90:` followed by `elif score >= 80:` guarantee about ordering?",
    options: [
      "The order doesn't matter",
      "Higher thresholds must come first, or lower ones would match prematurely",
      "elif must come before if",
      "Both branches run",
    ],
    answer: 1,
    explain: "Because the first matching branch wins, you must test the highest threshold first; otherwise a 95 would wrongly match a lower elif.",
  }
);
