// ── Chapter 08 — Modules & Packages ─────────────────────────────────────────
QUESTIONS["08"] = [
  {
    q: "What is a Python module?",
    options: [
      "A single .py file containing definitions and code you can import",
      "A compiled executable",
      "A type of loop",
      "A virtual environment",
    ],
    answer: 0,
    explain: "A module is a .py file whose functions, classes, and variables can be imported and reused elsewhere.",
  },
  {
    q: "How do you import the standard math module?",
    options: ["include math", "import math", "using math", "require math"],
    answer: 1,
    explain: "`import math` makes the module available; you then access members with math.sqrt(), math.pi, etc.",
  },
  {
    q: "What does 'from math import sqrt' let you write?",
    options: ["math.sqrt(9)", "sqrt(9)", "import sqrt(9)", "math(sqrt(9))"],
    answer: 1,
    explain: "from-import brings the name directly into scope, so you call sqrt(9) without the math. prefix.",
  },
  {
    q: "What does 'import numpy as np' do?",
    options: [
      "Renames the numpy package permanently",
      "Imports numpy under the local alias np",
      "Imports only part of numpy",
      "Fails unless numpy is renamed on disk",
    ],
    answer: 1,
    explain: "`as np` gives the imported module a shorter local alias; np.array(...) is the common convention.",
  },
  {
    q: "What is the value of __name__ when a file is run directly?",
    options: ["The file name", "'__main__'", "'main'", "None"],
    answer: 1,
    explain: "When a script is executed directly, its __name__ is '__main__'. When imported, __name__ is the module's name.",
  },
  {
    q: "What is the purpose of `if __name__ == '__main__':`?",
    options: [
      "To define the main function",
      "To run code only when the file is executed directly, not when imported",
      "To rename the module",
      "To import main",
    ],
    answer: 1,
    explain: "This guard lets a file act as both an importable module and a runnable script — the guarded code runs only on direct execution.",
  },
  {
    q: "Which standard library module provides random numbers?",
    options: ["rand", "random", "randomizer", "numbers"],
    answer: 1,
    explain: "The `random` module provides random(), randint(), choice(), shuffle(), and more.",
  },
  {
    q: "What does random.randint(1, 6) return?",
    options: [
      "A float between 1 and 6",
      "An integer from 1 to 6 inclusive",
      "An integer from 1 to 5",
      "Always 1",
    ],
    answer: 1,
    explain: "random.randint(a, b) returns a random integer N with a <= N <= b — both endpoints included.",
  },
  {
    q: "Which module provides operating-system paths and environment access?",
    options: ["os", "sys", "path", "system"],
    answer: 0,
    explain: "The `os` module exposes OS features like os.path, os.getcwd(), os.listdir(), and os.environ.",
  },
  {
    q: "What does sys.argv contain?",
    options: [
      "Environment variables",
      "The command-line arguments passed to the script",
      "The Python version",
      "Imported modules",
    ],
    answer: 1,
    explain: "sys.argv is a list of command-line arguments; sys.argv[0] is the script name and the rest are the passed arguments.",
  },
  {
    q: "Which module handles dates and times?",
    options: ["time only", "datetime", "calendar only", "clock"],
    answer: 1,
    explain: "The `datetime` module provides date, time, datetime, and timedelta types for working with dates and times.",
  },
  {
    q: "What does collections.Counter(['a','b','a']) produce?",
    options: [
      "Counter({'a': 2, 'b': 1})",
      "{'a', 'b'}",
      "['a', 'b', 'a']",
      "3",
    ],
    answer: 0,
    explain: "Counter tallies occurrences of each element, giving Counter({'a': 2, 'b': 1}).",
  },
  {
    q: "What does collections.defaultdict(int) give a missing key on first access?",
    options: ["KeyError", "None", "0 (int() default)", "An empty list"],
    answer: 2,
    explain: "defaultdict(int) calls int() for missing keys, producing 0 — handy for counting without pre-checking keys.",
  },
  {
    q: "What does itertools provide?",
    options: [
      "File tools",
      "Efficient iterator building blocks like count, cycle, chain, combinations",
      "Math constants",
      "GUI widgets",
    ],
    answer: 1,
    explain: "itertools offers fast, memory-efficient iterators such as chain(), product(), combinations(), and permutations().",
  },
  {
    q: "What makes a directory a Python package (classically)?",
    options: [
      "A README file",
      "An __init__.py file",
      "A requirements.txt",
      "A .package extension",
    ],
    answer: 1,
    explain: "A package is a directory of modules; historically an __init__.py file marks it as a package (it can be empty).",
  },
  {
    q: "What does the __init__.py file's presence let you do?",
    options: [
      "Nothing",
      "Treat the folder as a package and control what its import exposes",
      "Run the folder as a script",
      "Delete the package",
    ],
    answer: 1,
    explain: "__init__.py runs on package import and can expose sub-modules or set __all__, shaping the package's public API.",
  },
  {
    q: "What does math.pi provide?",
    options: [
      "The number of digits of pi",
      "The floating-point constant 3.14159...",
      "A function to compute pi",
      "The letter p",
    ],
    answer: 1,
    explain: "math.pi is the constant π ≈ 3.141592653589793.",
  },
  {
    q: "What does 'from module import *' do (and why is it discouraged)?",
    options: [
      "Imports nothing",
      "Imports all public names, which can clutter the namespace and cause name clashes",
      "Imports only classes",
      "Runs the module twice",
    ],
    answer: 1,
    explain: "Star-import pulls in all public names, making it unclear where names came from and risking collisions. Prefer explicit imports.",
  },
  {
    q: "What is the conventional pattern for a script's entry point?",
    options: [
      "Put all code at module top level",
      "Define a main() function and call it under the __name__ guard",
      "Use only lambdas",
      "Avoid functions entirely",
    ],
    answer: 1,
    explain: "Defining main() and calling it under `if __name__ == '__main__':` keeps the module importable and testable while still runnable.",
  },
  {
    q: "What does __all__ = ['foo'] in a module control?",
    options: [
      "The module's version",
      "Which names 'from module import *' exposes",
      "The import order",
      "The docstring",
    ],
    answer: 1,
    explain: "__all__ defines the public names exported by `from module import *`, limiting what star-import brings in.",
  },
  {
    q: "Which import style is generally preferred for clarity?",
    options: [
      "from module import *",
      "Explicit imports (import module OR from module import specific_name)",
      "Importing inside every function",
      "No imports at all",
    ],
    answer: 1,
    explain: "Explicit imports make dependencies and name origins clear, which improves readability and avoids namespace pollution.",
  },
  {
    q: "What does os.path.join('data', 'f.txt') do?",
    options: [
      "Reads the file",
      "Joins path parts with the correct OS separator",
      "Creates the file",
      "Splits the path",
    ],
    answer: 1,
    explain: "os.path.join builds a path using the platform's separator, e.g. 'data/f.txt' or 'data\\\\f.txt'.",
  },
  {
    q: "What does random.choice(['a','b','c']) return?",
    options: [
      "The whole list",
      "One randomly selected element",
      "The first element",
      "A shuffled list",
    ],
    answer: 1,
    explain: "random.choice() returns a single element chosen at random from the sequence.",
  },
  {
    q: "What does a relative import like 'from .helpers import x' require?",
    options: [
      "Being inside a package",
      "An internet connection",
      "A virtual environment",
      "A global variable",
    ],
    answer: 0,
    explain: "Relative imports (with a leading dot) only work within a package; running the file as a top-level script would fail.",
  },
  {
    q: "What does datetime.date.today() return?",
    options: [
      "The current time only",
      "Today's date (year, month, day)",
      "A timestamp string",
      "The day of week number",
    ],
    answer: 1,
    explain: "datetime.date.today() returns a date object for the current local date.",
  },
  {
    q: "What is the Python Standard Library?",
    options: [
      "Third-party packages from PyPI",
      "The large set of modules bundled with Python (math, os, json, random, etc.)",
      "A single module",
      "Only available with pip",
    ],
    answer: 1,
    explain: "The Standard Library ships with the interpreter — you can import its modules without installing anything.",
  },
];
