// ── Chapter 02 — Core Language · expansion pool ─────────────────────────────
QUESTIONS["02"].push(
  {
    q: "What does 10 / 4 evaluate to in Python 3?",
    options: ["2", "2.5", "2.0", "3"],
    answer: 1,
    explain: "The single `/` is true division and always returns a float: 10 / 4 is 2.5.",
  },
  {
    q: "What does -7 // 2 evaluate to?",
    options: ["-3", "-4", "-3.5", "3"],
    answer: 1,
    explain: "Floor division rounds toward negative infinity, so -7 // 2 is -4 (not -3).",
  },
  {
    q: "What is the value of 2 + 3 * 4?",
    options: ["20", "14", "24", "9"],
    answer: 1,
    explain: "Multiplication has higher precedence than addition: 3 * 4 = 12, then + 2 = 14.",
  },
  {
    q: "What does x += 3 mean when x = 5?",
    options: ["x becomes 3", "x becomes 8 (x = x + 3)", "x becomes 15", "Error"],
    answer: 1,
    explain: "`+=` is augmented assignment: x += 3 is shorthand for x = x + 3, giving 8.",
  },
  {
    q: "What does 'hello'.capitalize() return?",
    options: ["'HELLO'", "'Hello'", "'hello'", "'hELLO'"],
    answer: 1,
    explain: ".capitalize() uppercases the first character and lowercases the rest: 'Hello'.",
  },
  {
    q: "What does 'hello world'.title() return?",
    options: ["'Hello World'", "'HELLO WORLD'", "'Hello world'", "'hello world'"],
    answer: 0,
    explain: ".title() capitalizes the first letter of each word: 'Hello World'.",
  },
  {
    q: "What does 'banana'.count('a') return?",
    options: ["2", "3", "1", "6"],
    answer: 1,
    explain: ".count() returns how many times the substring appears; 'a' occurs 3 times in 'banana'.",
  },
  {
    q: "What does 'banana'.find('na') return?",
    options: ["-1", "2", "0", "4"],
    answer: 1,
    explain: ".find() returns the index of the first match; 'na' first appears at index 2. (It returns -1 if not found.)",
  },
  {
    q: "What is the difference between .find() and .index() for strings?",
    options: [
      "They are identical",
      ".find() returns -1 when not found; .index() raises ValueError",
      ".index() is faster",
      ".find() only works on lists",
    ],
    answer: 1,
    explain: "Both locate a substring, but .find() returns -1 on failure while .index() raises a ValueError.",
  },
  {
    q: "What does 'Hello'.replace('l', 'L') return?",
    options: ["'HeLLo'", "'HeLlo'", "'Hello'", "'HELLO'"],
    answer: 0,
    explain: ".replace() swaps every occurrence by default, so both l's become L: 'HeLLo'.",
  },
  {
    q: "What does 'file.txt'.startswith('file') return?",
    options: ["True", "False", "'file'", "1"],
    answer: 0,
    explain: ".startswith() returns a bool indicating whether the string begins with the given prefix — True here.",
  },
  {
    q: "What does 'report.pdf'.endswith('.pdf') return?",
    options: ["True", "False", "'.pdf'", "None"],
    answer: 0,
    explain: ".endswith() checks the suffix, returning True because the string ends with '.pdf'.",
  },
  {
    q: "What does '-'.join(['a', 'b', 'c']) return?",
    options: ["'abc'", "'a-b-c'", "['a-b-c']", "'-abc-'"],
    answer: 1,
    explain: "str.join() concatenates the iterable's items using the string as separator: 'a-b-c'.",
  },
  {
    q: "What does '5'.zfill(3) return?",
    options: ["'005'", "'500'", "'5  '", "'  5'"],
    answer: 0,
    explain: ".zfill(width) pads the string on the left with zeros to the given width: '005'.",
  },
  {
    q: "What does 'Hi'.isalpha() return?",
    options: ["True", "False", "'Hi'", "2"],
    answer: 0,
    explain: ".isalpha() is True when every character is a letter and the string is non-empty — True for 'Hi'.",
  },
  {
    q: "What does '123'.isdigit() return?",
    options: ["True", "False", "123", "'123'"],
    answer: 0,
    explain: ".isdigit() returns True when all characters are digits; '123' qualifies.",
  },
  {
    q: "What does 'a\\tb' contain between a and b?",
    options: ["A literal backslash-t", "A tab character", "A newline", "Two spaces"],
    answer: 1,
    explain: "\\t is the escape sequence for a tab character, so 'a\\tb' has a tab between a and b.",
  },
  {
    q: "What does the r prefix in r'C:\\new' do?",
    options: [
      "Reverses the string",
      "Makes it a raw string so backslashes are literal (no escape processing)",
      "Repeats it",
      "Rounds it",
    ],
    answer: 1,
    explain: "A raw string (r'...') treats backslashes literally, so \\n isn't a newline — handy for Windows paths and regex.",
  },
  {
    q: "How do you write a multi-line string literal?",
    options: [
      "Use \\n only",
      "Wrap it in triple quotes (''' or \"\"\")",
      "Use square brackets",
      "You cannot",
    ],
    answer: 1,
    explain: "Triple-quoted strings span multiple lines and preserve the embedded newlines.",
  },
  {
    q: "What does round(2.675, 2) approximately return?",
    options: ["2.68", "2.67", "3", "2.7"],
    answer: 1,
    explain: "Because 2.675 can't be represented exactly in binary floating point, round(2.675, 2) yields 2.67, a classic float-precision surprise.",
  },
  {
    q: "What does abs(-4.5) return?",
    options: ["4.5", "-4.5", "4", "5"],
    answer: 0,
    explain: "abs() returns the absolute (non-negative) magnitude: 4.5.",
  },
  {
    q: "What does divmod(17, 5) return?",
    options: ["(3, 2)", "(2, 3)", "3.4", "(5, 17)"],
    answer: 0,
    explain: "divmod(a, b) returns (a // b, a % b) as a tuple: (3, 2).",
  },
  {
    q: "What does bin(5) return?",
    options: ["'101'", "'0b101'", "5", "'0x5'"],
    answer: 1,
    explain: "bin() returns the binary string with a '0b' prefix: '0b101'.",
  },
  {
    q: "What does hex(255) return?",
    options: ["'0xff'", "'ff'", "'255'", "'0b11111111'"],
    answer: 0,
    explain: "hex() returns the hexadecimal string with a '0x' prefix: '0xff'.",
  },
  {
    q: "What does int('1010', 2) return?",
    options: ["1010", "10", "2", "Error"],
    answer: 1,
    explain: "int(string, base) parses the string in the given base; '1010' in base 2 is decimal 10.",
  },
  {
    q: "What does ord('A') return?",
    options: ["65", "97", "'A'", "1"],
    answer: 0,
    explain: "ord() returns the Unicode code point of a character; 'A' is 65. chr(65) reverses it.",
  },
  {
    q: "What does chr(97) return?",
    options: ["'a'", "'A'", "97", "'97'"],
    answer: 0,
    explain: "chr() converts a code point to its character; 97 is 'a'.",
  },
  {
    q: "What does 1_000_000 evaluate to?",
    options: ["An error", "1000000", "'1_000_000'", "1000"],
    answer: 1,
    explain: "Underscores are allowed as digit separators for readability; 1_000_000 is just the integer 1000000.",
  },
  {
    q: "What does f'{1000000:,}' produce?",
    options: ["'1000000'", "'1,000,000'", "'1.000.000'", "'1 000 000'"],
    answer: 1,
    explain: "The ',' format option inserts thousands separators: '1,000,000'.",
  },
  {
    q: "What does f'{0.5:.0%}' produce?",
    options: ["'0.5'", "'50%'", "'0%'", "'5%'"],
    answer: 1,
    explain: "The % type multiplies by 100 and appends a percent sign; with .0 precision it's '50%'.",
  },
  {
    q: "What does f'{42:5}' produce (width 5)?",
    options: ["'42'", "'   42'", "'42   '", "'00042'"],
    answer: 1,
    explain: "A bare width right-aligns numbers in a field of that width, padding with spaces: '   42'.",
  },
  {
    q: "What does f'{'hi':>5}' produce?",
    options: ["'hi   '", "'   hi'", "'hi'", "'  hi '"],
    answer: 1,
    explain: "'>' right-aligns within the width; the 3-space pad goes on the left: '   hi'.",
  },
  {
    q: "What does the debug f-string f'{x=}' produce when x = 7?",
    options: ["'7'", "'x=7'", "'x'", "'{x=}'"],
    answer: 1,
    explain: "The = specifier prints both the expression text and its value: 'x=7'. Great for quick debugging.",
  },
  {
    q: "What does bool(0.0) return?",
    options: ["True", "False", "0", "None"],
    answer: 1,
    explain: "Zero of any numeric type is falsy, so bool(0.0) is False.",
  },
  {
    q: "What does bool([]) return?",
    options: ["True", "False", "[]", "0"],
    answer: 1,
    explain: "An empty list is falsy, so bool([]) is False. A non-empty list is truthy.",
  },
  {
    q: "What does 'yes' if 0 else 'no' evaluate to?",
    options: ["'yes'", "'no'", "0", "None"],
    answer: 1,
    explain: "0 is falsy, so the conditional expression takes the else branch: 'no'.",
  },
  {
    q: "What does None or 'default' evaluate to?",
    options: ["None", "'default'", "True", "''"],
    answer: 1,
    explain: "`or` returns the first truthy operand; None is falsy, so it returns 'default' — a common defaulting idiom.",
  },
  {
    q: "What does 5 and 3 evaluate to?",
    options: ["True", "3", "5", "8"],
    answer: 1,
    explain: "`and` returns the last operand if all are truthy (short-circuit returns the value, not a bool): 3.",
  },
  {
    q: "What does type(True) report?",
    options: ["<class 'bool'>", "<class 'int'>", "<class 'str'>", "<class 'True'>"],
    answer: 0,
    explain: "True is a bool. (Interestingly bool is a subclass of int, so True == 1, but type(True) is bool.)",
  },
  {
    q: "What does isinstance(3, int) return?",
    options: ["True", "False", "int", "3"],
    answer: 0,
    explain: "isinstance(obj, type) tests whether obj is an instance of the type; 3 is an int, so True.",
  },
  {
    q: "What does 'abc'[1:] return?",
    options: ["'bc'", "'ab'", "'a'", "'abc'"],
    answer: 0,
    explain: "Omitting the stop slices to the end; [1:] gives everything from index 1: 'bc'.",
  },
  {
    q: "What does 'Python'[::-1] return?",
    options: ["'Python'", "'nohtyP'", "'P'", "'n'"],
    answer: 1,
    explain: "A step of -1 reverses the string: 'nohtyP'.",
  },
  {
    q: "What does 'e' in 'hello' evaluate to?",
    options: ["True", "False", "1", "'e'"],
    answer: 0,
    explain: "The `in` operator tests substring membership; 'e' appears in 'hello', so True.",
  },
  {
    q: "What does str(3.0) produce?",
    options: ["'3'", "'3.0'", "3.0", "3"],
    answer: 1,
    explain: "str() of the float 3.0 preserves the decimal: '3.0'.",
  }
);
