// ── Chapter 04 — Functions ──────────────────────────────────────────────────
QUESTIONS["04"] = [
  {
    q: "Which keyword defines a function in Python?",
    options: ["function", "def", "func", "lambda"],
    answer: 1,
    explain: "`def` starts a function definition: `def name(params):`. `lambda` creates small anonymous functions.",
  },
  {
    q: "What does a function return if it has no return statement?",
    options: ["0", "'' (empty string)", "None", "It raises an error"],
    answer: 2,
    explain: "A function without an explicit return (or with a bare `return`) returns None.",
  },
  {
    q: "In def greet(name='World'):, what is 'World'?",
    options: [
      "A required argument",
      "A default parameter value",
      "A keyword-only argument",
      "A return value",
    ],
    answer: 1,
    explain: "'World' is a default value; if the caller omits `name`, it defaults to 'World'.",
  },
  {
    q: "What does *args collect in a function signature?",
    options: [
      "Extra keyword arguments as a dict",
      "Extra positional arguments as a tuple",
      "Only the first argument",
      "Nothing",
    ],
    answer: 1,
    explain: "*args gathers any extra positional arguments into a tuple, letting a function accept a variable number of positional values.",
  },
  {
    q: "What does **kwargs collect?",
    options: [
      "Extra positional arguments as a list",
      "Extra keyword arguments as a dictionary",
      "The return value",
      "Default values",
    ],
    answer: 1,
    explain: "**kwargs gathers extra keyword arguments into a dict, mapping argument names to values.",
  },
  {
    q: "What is a docstring?",
    options: [
      "A comment starting with #",
      "A string literal right after the def line that documents the function",
      "A required return value",
      "A type annotation",
    ],
    answer: 1,
    explain: "A docstring is a string (usually triple-quoted) placed as the first statement in a function/module/class; it's accessible via help() and __doc__.",
  },
  {
    q: "What does this return?  def add(a, b): return a + b\\nadd(2, 3)",
    options: ["5", "'23'", "None", "23"],
    answer: 0,
    explain: "The function returns a + b = 2 + 3 = 5.",
  },
  {
    q: "What are 'keyword arguments'?",
    options: [
      "Arguments passed by name, e.g. func(x=5)",
      "Reserved Python keywords",
      "Arguments that must be integers",
      "Arguments passed only positionally",
    ],
    answer: 0,
    explain: "Keyword arguments are passed by name (name=value), which improves readability and lets you skip or reorder optional parameters.",
  },
  {
    q: "What is a lambda?",
    options: [
      "A loop construct",
      "A small anonymous function written in one expression",
      "A module",
      "A type of variable",
    ],
    answer: 1,
    explain: "A lambda is an anonymous function: `lambda x: x * 2` is equivalent to a small def that returns x * 2.",
  },
  {
    q: "What does (lambda x: x * 2)(5) evaluate to?",
    options: ["10", "25", "5", "'xx'"],
    answer: 0,
    explain: "The lambda doubles its argument; called with 5, it returns 10.",
  },
  {
    q: "What is variable 'scope'?",
    options: [
      "The data type of a variable",
      "The region of code where a name is accessible",
      "The memory size of a variable",
      "The number of times it's used",
    ],
    answer: 1,
    explain: "Scope is where a name is visible. Names assigned inside a function are local to that function unless declared global/nonlocal.",
  },
  {
    q: "What does the `global` keyword do inside a function?",
    options: [
      "Creates a new local variable",
      "Lets the function rebind a variable defined at module (global) scope",
      "Makes a variable constant",
      "Imports a module",
    ],
    answer: 1,
    explain: "global tells Python that assignments to that name should affect the module-level variable instead of creating a local one.",
  },
  {
    q: "What does 'functions are first-class objects' mean?",
    options: [
      "Functions run faster than other code",
      "Functions can be assigned to variables, passed as arguments, and returned",
      "Functions must be defined first in a file",
      "Only built-in functions are allowed",
    ],
    answer: 1,
    explain: "Being first-class means functions are ordinary objects: you can store them in variables, pass them to other functions, and return them.",
  },
  {
    q: "What is printed?  def f(x):\\n    x = x + 1\\nn = 5\\nf(n)\\nprint(n)",
    options: ["6", "5", "None", "Error"],
    answer: 1,
    explain: "Integers are immutable and passed by object reference; reassigning x inside f doesn't change n, so it stays 5.",
  },
  {
    q: "Why can a mutable default argument like def f(items=[]) be risky?",
    options: [
      "It is a syntax error",
      "The same list is shared across calls, so it accumulates values between calls",
      "It runs slower",
      "It converts to a tuple",
    ],
    answer: 1,
    explain: "Default values are evaluated once at definition time, so a mutable default (like []) persists and is shared across calls. Use None and create a fresh list inside instead.",
  },
  {
    q: "How do you return multiple values from a function?",
    options: [
      "You cannot",
      "Return them comma-separated; Python packs them into a tuple",
      "Use two return statements",
      "Use *return",
    ],
    answer: 1,
    explain: "`return a, b` returns a tuple (a, b), which the caller can unpack: x, y = func().",
  },
  {
    q: "What does this print?  def outer():\\n    def inner():\\n        return 3\\n    return inner()\\nprint(outer())",
    options: ["3", "inner", "None", "Error"],
    answer: 0,
    explain: "outer defines and calls inner(), which returns 3, so outer() returns 3.",
  },
  {
    q: "What is the correct way to call a function with a keyword argument?",
    options: ["greet(name: 'Sam')", "greet(name='Sam')", "greet('name'='Sam')", "greet[name='Sam']"],
    answer: 1,
    explain: "Keyword arguments use `name=value` syntax inside the parentheses: greet(name='Sam').",
  },
  {
    q: "Can a function be assigned to a variable, e.g. f = len?",
    options: [
      "No, that's illegal",
      "Yes; f now refers to the function and f('hi') returns 2",
      "Only for lambdas",
      "Only inside a class",
    ],
    answer: 1,
    explain: "Functions are objects, so f = len makes f another name for len; f('hi') returns 2.",
  },
  {
    q: "What does the return statement do?",
    options: [
      "Prints a value",
      "Ends the function and sends a value back to the caller",
      "Starts a loop",
      "Declares a variable",
    ],
    answer: 1,
    explain: "return exits the function immediately and passes its value back to the caller (or None if no value given).",
  },
  {
    q: "In def f(a, b, *args), calling f(1, 2, 3, 4) makes args equal to what?",
    options: ["(3, 4)", "[3, 4]", "(1, 2, 3, 4)", "3"],
    answer: 0,
    explain: "a=1, b=2 consume the first two; the remaining positional values are packed into the tuple args = (3, 4).",
  },
  {
    q: "What does help(func) or func.__doc__ display?",
    options: [
      "The function's source code",
      "The function's docstring",
      "The function's return value",
      "Nothing",
    ],
    answer: 1,
    explain: "Both surface the function's docstring — the documentation string written just under the def line.",
  },
  {
    q: "Which is a valid one-line function using lambda assigned to square?",
    options: [
      "square = lambda x: x ** 2",
      "square = def x: x ** 2",
      "lambda square(x): x ** 2",
      "square = function(x): x ** 2",
    ],
    answer: 0,
    explain: "`square = lambda x: x ** 2` binds the anonymous function to the name square; square(4) returns 16.",
  },
  {
    q: "What does sorted(nums, key=lambda x: -x) do?",
    options: [
      "Sorts ascending",
      "Sorts descending by using the negation as the sort key",
      "Reverses the string",
      "Raises an error",
    ],
    answer: 1,
    explain: "The key function negates each value, so sorting ascending on -x effectively sorts the original values descending.",
  },
  {
    q: "What is a 'positional argument'?",
    options: [
      "An argument matched to a parameter by its position/order",
      "An argument passed by name",
      "An argument with a default",
      "A global variable",
    ],
    answer: 0,
    explain: "Positional arguments are matched to parameters left-to-right by their position in the call.",
  },
  {
    q: "What happens if you call def f(a, b) as f(1)?",
    options: [
      "b defaults to 0",
      "TypeError: missing required argument 'b'",
      "It returns None",
      "b becomes None automatically",
    ],
    answer: 1,
    explain: "Without a default for b, omitting it raises a TypeError about the missing required positional argument.",
  },
];
