// ── Chapter 05 — Data Structures · expansion pool ───────────────────────────
QUESTIONS["05"].push(
  {
    q: "What does [1, 2].insert(1, 9) produce in the list?",
    options: ["[1, 9, 2]", "[9, 1, 2]", "[1, 2, 9]", "[1, 9]"],
    answer: 0,
    explain: "insert(index, value) places the value before the given index; inserting 9 at index 1 gives [1, 9, 2].",
  },
  {
    q: "What does [1, 2, 3].remove(2) do?",
    options: [
      "Removes the element at index 2",
      "Removes the first occurrence of the value 2",
      "Removes the last element",
      "Returns 2",
    ],
    answer: 1,
    explain: "list.remove(x) deletes the first element equal to x (by value), leaving [1, 3].",
  },
  {
    q: "What is the difference between del lst[0] and lst.remove(0)?",
    options: [
      "They are identical",
      "del removes by index; remove deletes by value",
      "remove is faster",
      "del only works on dicts",
    ],
    answer: 1,
    explain: "del lst[0] removes the item at index 0; lst.remove(0) removes the first element whose value is 0.",
  },
  {
    q: "What does [1, 2].extend([3, 4]) produce?",
    options: ["[1, 2, [3, 4]]", "[1, 2, 3, 4]", "[[1,2],[3,4]]", "Error"],
    answer: 1,
    explain: "extend appends each item of the iterable individually: [1, 2, 3, 4]. (append would nest the list.)",
  },
  {
    q: "What does [1, 2].append([3, 4]) produce?",
    options: ["[1, 2, 3, 4]", "[1, 2, [3, 4]]", "[[1,2],3,4]", "Error"],
    answer: 1,
    explain: "append adds its argument as a single element, so the list becomes [1, 2, [3, 4]].",
  },
  {
    q: "What does 'abc'.index('b') plus [10,20,30].index(20) both illustrate?",
    options: [
      "index returns the value",
      "index returns the position of the first matching item",
      "index removes the item",
      "index only works on strings",
    ],
    answer: 1,
    explain: ".index(x) returns the first position where x is found (1 in both cases here).",
  },
  {
    q: "What does [3, 1, 2].reverse() do and return?",
    options: [
      "Returns [2,1,3]",
      "Reverses in place and returns None",
      "Sorts the list",
      "Returns a copy",
    ],
    answer: 1,
    explain: "list.reverse() reverses the list in place and returns None (like sort()).",
  },
  {
    q: "What does list1 + list2 do?",
    options: [
      "Adds elements pairwise",
      "Concatenates into a new list",
      "Mutates list1",
      "Errors",
    ],
    answer: 1,
    explain: "The + operator concatenates two lists into a brand-new list; the originals are unchanged.",
  },
  {
    q: "What does [0] * 3 produce?",
    options: ["[0, 0, 0]", "[0, 3]", "[3]", "0"],
    answer: 0,
    explain: "Multiplying a list by an int repeats its contents: [0, 0, 0].",
  },
  {
    q: "Why can [[0]*3]*3 be a trap?",
    options: [
      "It errors",
      "The inner lists are the same object, so changing one row changes all",
      "It's too slow",
      "It creates tuples",
    ],
    answer: 1,
    explain: "The outer * copies the reference, so all three rows point to one list; mutating one appears in all. Use a comprehension instead.",
  },
  {
    q: "What does a shallow copy (list.copy()) NOT do?",
    options: [
      "Copy the outer list",
      "Deep-copy nested mutable objects (they're shared)",
      "Return a new list",
      "Preserve order",
    ],
    answer: 1,
    explain: "A shallow copy duplicates the top level but nested objects are still shared references; use copy.deepcopy for full independence.",
  },
  {
    q: "What does (1, 2, 3).count(2) return?",
    options: ["1", "2", "0", "3"],
    answer: 0,
    explain: "Tuples support count() and index(); 2 appears once.",
  },
  {
    q: "What happens when you try t[0] = 9 on a tuple t?",
    options: [
      "It works",
      "TypeError — tuples don't support item assignment",
      "It appends 9",
      "It returns a new tuple",
    ],
    answer: 1,
    explain: "Tuples are immutable, so item assignment raises TypeError.",
  },
  {
    q: "What does nested unpacking a, (b, c) = 1, (2, 3) assign to b?",
    options: ["1", "2", "3", "(2,3)"],
    answer: 1,
    explain: "The tuple structure is unpacked in parallel: a=1, b=2, c=3. So b is 2.",
  },
  {
    q: "What does {1, 2, 3} - {2} produce?",
    options: ["{1, 3}", "{2}", "{1, 2, 3}", "{}"],
    answer: 0,
    explain: "`-` is set difference: elements in the left set not in the right — {1, 3}.",
  },
  {
    q: "What does {1, 2} ^ {2, 3} produce?",
    options: ["{1, 3}", "{2}", "{1, 2, 3}", "{1,2,2,3}"],
    answer: 0,
    explain: "`^` is symmetric difference — elements in exactly one set: {1, 3}.",
  },
  {
    q: "What is the difference between set.remove(x) and set.discard(x)?",
    options: [
      "None",
      "remove raises KeyError if x is absent; discard does not",
      "discard is slower",
      "remove returns the item",
    ],
    answer: 1,
    explain: "Both delete x, but remove raises KeyError when x isn't present, while discard silently does nothing.",
  },
  {
    q: "What does {1, 2}.issubset({1, 2, 3}) return?",
    options: ["True", "False", "{1,2}", "Error"],
    answer: 0,
    explain: "Every element of {1,2} is in {1,2,3}, so it's a subset — True.",
  },
  {
    q: "What is a frozenset?",
    options: [
      "A sorted set",
      "An immutable, hashable version of a set",
      "A set of frozen values",
      "A deprecated type",
    ],
    answer: 1,
    explain: "frozenset is like set but immutable and hashable, so it can be a dict key or a member of another set.",
  },
  {
    q: "What does d.update({'b': 3}) do to d = {'a': 1, 'b': 2}?",
    options: [
      "Adds a new 'b'",
      "Overwrites d['b'] with 3",
      "Errors on duplicate key",
      "Removes 'b'",
    ],
    answer: 1,
    explain: "update merges the mapping in, overwriting existing keys, so d['b'] becomes 3.",
  },
  {
    q: "What does d.pop('a') do for d = {'a': 1}?",
    options: [
      "Returns 1 and removes the key 'a'",
      "Returns 'a'",
      "Removes the last item",
      "Errors",
    ],
    answer: 0,
    explain: "dict.pop(key) removes the key and returns its value (1), leaving the dict without 'a'.",
  },
  {
    q: "What does d.setdefault('x', 0) do if 'x' is absent?",
    options: [
      "Raises KeyError",
      "Inserts 'x': 0 and returns 0",
      "Returns None",
      "Deletes 'x'",
    ],
    answer: 1,
    explain: "setdefault returns the existing value or, if the key is missing, inserts it with the default and returns that default.",
  },
  {
    q: "What does dict.fromkeys(['a', 'b'], 0) create?",
    options: [
      "{'a': 0, 'b': 0}",
      "{'a': 'b'}",
      "{0: 'a', 0: 'b'}",
      "['a', 'b']",
    ],
    answer: 0,
    explain: "fromkeys builds a dict with each key mapped to the same default value: {'a': 0, 'b': 0}.",
  },
  {
    q: "In Python 3.7+, what order do dict keys iterate in?",
    options: [
      "Random",
      "Insertion order",
      "Sorted order",
      "Reverse order",
    ],
    answer: 1,
    explain: "Since 3.7, dicts preserve insertion order, so iteration reflects the order keys were added.",
  },
  {
    q: "What does len({'a': [1,2], 'b': [3]}) return?",
    options: ["2", "3", "5", "1"],
    answer: 0,
    explain: "len of a dict counts keys, not nested values, so it's 2.",
  },
  {
    q: "What does list(d.values()) give for d = {'a': 1, 'b': 2}?",
    options: ["['a', 'b']", "[1, 2]", "[('a',1),('b',2)]", "2"],
    answer: 1,
    explain: ".values() yields the values; listed it's [1, 2].",
  },
  {
    q: "What does 'x' not in {'a': 1} evaluate to?",
    options: ["True", "False", "KeyError", "None"],
    answer: 0,
    explain: "Membership checks keys; 'x' is not a key, so `not in` is True.",
  },
  {
    q: "What does sorted({'b': 2, 'a': 1}) return?",
    options: ["['a', 'b']", "[1, 2]", "{'a':1,'b':2}", "[('a',1),('b',2)]"],
    answer: 0,
    explain: "Iterating/sorting a dict works on its keys, so sorted() returns the sorted keys ['a', 'b'].",
  },
  {
    q: "What does max(d, key=d.get) return for d = {'a': 3, 'b': 7}?",
    options: ["'b'", "'a'", "7", "('b',7)"],
    answer: 0,
    explain: "Iterating the dict yields keys; key=d.get compares by value, so the key with the largest value ('b') is returned.",
  },
  {
    q: "What does nested access d['user']['name'] require?",
    options: [
      "d to be a list",
      "d['user'] to itself be a dict containing 'name'",
      "A default value",
      "A tuple key",
    ],
    answer: 1,
    explain: "Chained subscripting drills into nested structures; d['user'] must be a dict that has a 'name' key.",
  },
  {
    q: "What does a set comprehension {x % 3 for x in range(6)} produce?",
    options: ["{0, 1, 2}", "{0,1,2,0,1,2}", "[0,1,2]", "{0,1,2,3,4,5}"],
    answer: 0,
    explain: "The remainders cycle 0,1,2,0,1,2 but the set keeps only unique values: {0, 1, 2}.",
  },
  {
    q: "What does 'listcomp' [x for x in nums if x] filter out?",
    options: [
      "Nothing",
      "Falsy values (0, '', None, etc.)",
      "Odd numbers",
      "Duplicates",
    ],
    answer: 1,
    explain: "The bare `if x` keeps only truthy items, dropping falsy ones like 0, '', and None.",
  },
  {
    q: "What is the time complexity of `x in a_set` vs `x in a_list` (typical)?",
    options: [
      "Both O(1)",
      "Set is O(1) average; list is O(n)",
      "Both O(n)",
      "Set is O(n); list is O(1)",
    ],
    answer: 1,
    explain: "Sets use hashing for O(1) average membership; lists scan linearly, O(n).",
  },
  {
    q: "What does 'a, b, *rest = [1, 2, 3, 4, 5]' assign to rest?",
    options: ["[3, 4, 5]", "5", "[4, 5]", "(3,4,5)"],
    answer: 0,
    explain: "After a=1 and b=2, *rest gathers the remaining items into the list [3, 4, 5].",
  },
  {
    q: "What does '*init, last = [1, 2, 3]' assign to last?",
    options: ["3", "[3]", "1", "[1,2]"],
    answer: 0,
    explain: "Starred unpacking can appear first; *init takes [1, 2] and last takes 3.",
  },
  {
    q: "What does nums[-2:] return for nums = [1, 2, 3, 4]?",
    options: ["[3, 4]", "[1, 2]", "[4]", "[2, 3]"],
    answer: 0,
    explain: "A negative start slices from that many items before the end: the last two, [3, 4].",
  },
  {
    q: "What does 'a' * 3 in a list, ['a'] * 3, produce vs 'a' + 'a' + 'a'?",
    options: [
      "Both produce 'aaa'",
      "['a','a','a'] vs 'aaa' — one is a list, one is a string",
      "Both produce a list",
      "Error",
    ],
    answer: 1,
    explain: "['a'] * 3 repeats the list element into ['a','a','a']; string 'a'*3 concatenates into 'aaa'.",
  },
  {
    q: "What does collections.Counter('mississippi').most_common(1) return?",
    options: [
      "[('i', 4)]",
      "[('s', 4)]",
      "[('m', 1)]",
      "['i']",
    ],
    answer: 0,
    explain: "'i' and 's' both appear 4 times; most_common returns the highest count first, and 'i' appears earlier at that count, giving [('i', 4)].",
  },
  {
    q: "What does d.get('k', []) return when 'k' is missing?",
    options: ["None", "[]", "KeyError", "'k'"],
    answer: 1,
    explain: "The default second argument is returned for a missing key; here an empty list [].",
  },
  {
    q: "What is a good structure to represent a record with named fields when immutability is desired?",
    options: [
      "list",
      "collections.namedtuple (or a frozen dataclass)",
      "set",
      "plain tuple with magic indices",
    ],
    answer: 1,
    explain: "namedtuple gives immutable, indexable records with named fields — clearer than positional tuples.",
  },
  {
    q: "What does 'key in dict' NOT tell you?",
    options: [
      "Whether the key exists",
      "Whether a particular value exists",
      "Anything about membership",
      "The dict length",
    ],
    answer: 1,
    explain: "`in` on a dict tests keys only; to check values you'd use `value in d.values()`.",
  },
  {
    q: "What does list(zip(*[(1, 'a'), (2, 'b')])) produce (unzip)?",
    options: [
      "[(1, 2), ('a', 'b')]",
      "[(1, 'a'), (2, 'b')]",
      "[1, 2, 'a', 'b']",
      "Error",
    ],
    answer: 0,
    explain: "zip(*pairs) transposes/unzips: it groups first elements and second elements: [(1,2), ('a','b')].",
  },
  {
    q: "What does {**a, **b} do for two dicts a and b?",
    options: [
      "Errors",
      "Merges them into a new dict (b's keys win on conflict)",
      "Adds their values",
      "Creates a set",
    ],
    answer: 1,
    explain: "Dict unpacking merges both into a new dict; if a key appears in both, the later (b) value overrides.",
  },
  {
    q: "What does a.sort(key=len) do to a list of strings?",
    options: [
      "Sorts alphabetically",
      "Sorts by string length in place",
      "Reverses the list",
      "Errors",
    ],
    answer: 1,
    explain: "The key function sorts by each item's length, ordering shortest to longest, in place.",
  },
  {
    q: "What does nums.clear() do?",
    options: [
      "Returns a copy",
      "Removes all elements, leaving an empty list",
      "Deletes the variable",
      "Sorts the list",
    ],
    answer: 1,
    explain: "list.clear() empties the list in place, leaving [].",
  }
);
