// ── Chapter 06 — Comprehensions & Exceptions · expansion pool ───────────────
QUESTIONS["06"].push(
  {
    q: "What does [x**2 for x in range(5) if x % 2 == 0] produce?",
    options: ["[0, 4, 16]", "[0, 1, 4, 9, 16]", "[4, 16]", "[0, 2, 4]"],
    answer: 0,
    explain: "It squares only the even x (0, 2, 4): 0, 4, 16.",
  },
  {
    q: "What does [c.upper() for c in 'abc'] produce?",
    options: ["['A', 'B', 'C']", "'ABC'", "['a','b','c']", "['ABC']"],
    answer: 0,
    explain: "The comprehension uppercases each character into a list: ['A', 'B', 'C'].",
  },
  {
    q: "What does [[row[i] for row in m] for i in range(2)] do to a matrix m?",
    options: [
      "Copies m",
      "Transposes m (swaps rows and columns)",
      "Sums the rows",
      "Flattens m",
    ],
    answer: 1,
    explain: "The nested comprehension collects column i across all rows for each i — a transpose.",
  },
  {
    q: "What does [x for row in matrix for x in row] do?",
    options: [
      "Transposes",
      "Flattens a 2D list into a 1D list",
      "Filters evens",
      "Errors",
    ],
    answer: 1,
    explain: "The two for-clauses iterate rows then elements, flattening the nested list into one flat list.",
  },
  {
    q: "What is the order of clauses in a flattening comprehension [x for row in m for x in row]?",
    options: [
      "Inner loop first",
      "Same left-to-right order as nested for-loops (outer then inner)",
      "Reverse",
      "It doesn't matter",
    ],
    answer: 1,
    explain: "Multiple for-clauses read left-to-right exactly like nested loops: the first is outermost.",
  },
  {
    q: "What does {x: x**2 for x in range(3)} produce?",
    options: ["{0:0, 1:1, 2:4}", "[0,1,4]", "{0,1,4}", "{0:0,1:2,2:4}"],
    answer: 0,
    explain: "The dict comprehension maps each x to its square: {0:0, 1:1, 2:4}.",
  },
  {
    q: "What does {v: k for k, v in {'a': 1}.items()} produce?",
    options: ["{1: 'a'}", "{'a': 1}", "{'a': 'a'}", "{1: 1}"],
    answer: 0,
    explain: "It inverts the dict, swapping keys and values: {1: 'a'}.",
  },
  {
    q: "What is the memory advantage of sum(x*x for x in range(1000000))?",
    options: [
      "None",
      "The generator expression avoids building a full list in memory",
      "It runs on the GPU",
      "It caches results",
    ],
    answer: 1,
    explain: "Passing a generator expression streams values one at a time, so no large intermediate list is created.",
  },
  {
    q: "What does next(gen) do on a generator?",
    options: [
      "Restarts it",
      "Produces the next value, or raises StopIteration when exhausted",
      "Returns all values",
      "Closes it",
    ],
    answer: 1,
    explain: "next() advances the generator to its next yielded value; when there are none left it raises StopIteration.",
  },
  {
    q: "What does the yield keyword make a function?",
    options: [
      "A decorator",
      "A generator function that produces values lazily",
      "A coroutine only",
      "A class",
    ],
    answer: 1,
    explain: "A function containing yield becomes a generator; calling it returns a lazy iterator that yields values on demand.",
  },
  {
    q: "What does [x if x >= 0 else 0 for x in nums] do?",
    options: [
      "Filters negatives out",
      "Replaces negatives with 0, keeping length",
      "Errors",
      "Sorts nums",
    ],
    answer: 1,
    explain: "The ternary in the output expression maps negatives to 0 but keeps every element, so length is preserved.",
  },
  {
    q: "Where does the filter (if) go in [expr for x in it if cond]?",
    options: [
      "Before the for",
      "After the for-clause, to skip items",
      "Inside expr only",
      "It can't be used",
    ],
    answer: 1,
    explain: "A trailing `if cond` after the for filters which items are included (an `if...else` in front is a value choice, not a filter).",
  },
  {
    q: "What does a nested comprehension [f(x, y) for x in xs for y in ys] iterate like?",
    options: [
      "y outer, x inner",
      "x outer, y inner (all pairs)",
      "Only matching pairs",
      "Just xs",
    ],
    answer: 1,
    explain: "It's a double loop with x outer and y inner, producing every (x, y) combination.",
  },
  {
    q: "What exception does an undefined name like print(foo) raise?",
    options: ["ValueError", "NameError", "KeyError", "TypeError"],
    answer: 1,
    explain: "Referencing a name that isn't defined raises NameError.",
  },
  {
    q: "What exception does 'a' + 3 raise?",
    options: ["ValueError", "TypeError", "SyntaxError", "KeyError"],
    answer: 1,
    explain: "Adding incompatible types (str and int) raises TypeError.",
  },
  {
    q: "What exception does None.upper() raise?",
    options: ["AttributeError", "ValueError", "TypeError", "NameError"],
    answer: 0,
    explain: "None has no .upper() method, so accessing it raises AttributeError.",
  },
  {
    q: "What exception does an infinite recursion eventually raise?",
    options: ["StackError", "RecursionError", "MemoryError", "OverflowError"],
    answer: 1,
    explain: "Exceeding the recursion limit raises RecursionError.",
  },
  {
    q: "What does the assert statement do?",
    options: [
      "Prints a message",
      "Raises AssertionError if the condition is False",
      "Loops until True",
      "Nothing",
    ],
    answer: 1,
    explain: "assert cond, msg raises AssertionError with the optional message when cond is falsy — used for sanity checks.",
  },
  {
    q: "What does 'raise ValueError('bad') from err' express?",
    options: [
      "Suppresses the traceback",
      "Chains the new exception to the original cause err",
      "Catches err",
      "Retries",
    ],
    answer: 1,
    explain: "The `from` clause sets __cause__, linking the new exception to the original so the traceback shows both.",
  },
  {
    q: "What runs if a try block returns before finally?",
    options: [
      "finally is skipped",
      "finally still runs before the function actually returns",
      "It errors",
      "The return is cancelled",
    ],
    answer: 1,
    explain: "finally always executes — even when the try (or except) block hits a return — before control leaves the function.",
  },
  {
    q: "What does catching Exception (not BaseException) deliberately avoid catching?",
    options: [
      "ValueError",
      "System-exiting exceptions like KeyboardInterrupt and SystemExit",
      "TypeError",
      "KeyError",
    ],
    answer: 1,
    explain: "KeyboardInterrupt and SystemExit derive from BaseException but not Exception, so `except Exception` won't swallow them.",
  },
  {
    q: "What is wrong with `except:` (bare except)?",
    options: [
      "Nothing",
      "It catches everything including system signals, hiding bugs — prefer except Exception or specific types",
      "It's a syntax error",
      "It's faster",
    ],
    answer: 1,
    explain: "A bare except catches all exceptions (even KeyboardInterrupt), which can mask errors and make debugging hard.",
  },
  {
    q: "How do you access an exception's message in `except ValueError as e`?",
    options: ["e.message", "str(e) or e.args", "e.text", "e.value"],
    answer: 1,
    explain: "The message is available via str(e), and the arguments via e.args (a tuple).",
  },
  {
    q: "What does 'try/except/else' put in the else block?",
    options: [
      "Cleanup code",
      "Code that should run only if no exception occurred",
      "The risky code",
      "The error handler",
    ],
    answer: 1,
    explain: "The else runs when the try succeeded, keeping success-only logic separate from the guarded operation.",
  },
  {
    q: "What is EAFP?",
    options: [
      "A module name",
      "'Easier to Ask Forgiveness than Permission' — try the action, handle exceptions",
      "A loop pattern",
      "A data structure",
    ],
    answer: 1,
    explain: "EAFP is the Pythonic style of attempting an operation and catching exceptions, rather than pre-checking (LBYL).",
  },
  {
    q: "What context manager pattern replaces manual try/finally for files?",
    options: [
      "for loops",
      "the with statement",
      "assert",
      "global",
    ],
    answer: 1,
    explain: "`with open(...) as f:` uses a context manager to guarantee cleanup (closing) without an explicit finally.",
  },
  {
    q: "What does a custom exception typically subclass?",
    options: ["object", "Exception (or a more specific subclass)", "BaseException", "dict"],
    answer: 1,
    explain: "Custom exceptions should subclass Exception (or a relevant subclass) so they're caught by normal handlers.",
  },
  {
    q: "What does 'except (KeyError, IndexError) as e' catch?",
    options: [
      "Only KeyError",
      "Either a KeyError or an IndexError",
      "All exceptions",
      "Nothing",
    ],
    answer: 1,
    explain: "A tuple of exception types handles any listed type in one clause.",
  },
  {
    q: "What does a generator's lazy evaluation mean for [x for x in gen]?",
    options: [
      "It errors",
      "The comprehension consumes the generator, producing values on demand as it iterates",
      "It reverses the generator",
      "It caches the generator",
    ],
    answer: 1,
    explain: "Iterating a generator pulls values one at a time; wrapping it in a list comprehension consumes it fully into a list.",
  },
  {
    q: "What exception does opening a missing file raise?",
    options: ["IOError only", "FileNotFoundError", "ValueError", "KeyError"],
    answer: 1,
    explain: "Attempting to read a non-existent path raises FileNotFoundError (a subclass of OSError).",
  },
  {
    q: "What does 'raise' with no arguments outside an except block cause?",
    options: [
      "Nothing",
      "RuntimeError: No active exception to re-raise",
      "It exits cleanly",
      "It raises ValueError",
    ],
    answer: 1,
    explain: "A bare raise only works while handling an exception; outside one it raises RuntimeError.",
  },
  {
    q: "What does [n for n in range(20) if n % 3 == 0 if n % 2 == 0] produce?",
    options: [
      "[0, 6, 12, 18]",
      "[0, 3, 6, 9]",
      "[6, 12, 18]",
      "[0, 2, 4]",
    ],
    answer: 0,
    explain: "Two if-clauses act as combined conditions (divisible by 3 AND 2): 0, 6, 12, 18.",
  },
  {
    q: "What does len([x for x in 'hello' if x in 'aeiou']) return?",
    options: ["1", "2", "3", "5"],
    answer: 1,
    explain: "The vowels in 'hello' are 'e' and 'o' — 2 characters.",
  },
  {
    q: "What is a dict comprehension good for compared to a loop?",
    options: [
      "Nothing",
      "Building a dict from an iterable concisely in one expression",
      "Only filtering",
      "Sorting",
    ],
    answer: 1,
    explain: "Dict comprehensions build mappings compactly, e.g. {k: f(k) for k in keys}, more concise than an explicit loop.",
  },
  {
    q: "What does the walrus operator := allow inside a comprehension?",
    options: [
      "Nothing",
      "Assigning and reusing a computed value within the comprehension",
      "Multiple returns",
      "Type hints",
    ],
    answer: 1,
    explain: "The walrus operator binds a name to a value inline, e.g. [y for x in data if (y := f(x)) > 0], avoiding recomputation.",
  },
  {
    q: "What does this leave in result?  try:\\n    result = 10 / 0\\nexcept ZeroDivisionError:\\n    result = None",
    options: ["10", "0", "None", "Error"],
    answer: 2,
    explain: "The division raises ZeroDivisionError, the except handles it and sets result to None.",
  },
  {
    q: "What is the exception hierarchy relationship of ZeroDivisionError?",
    options: [
      "It subclasses ValueError",
      "It subclasses ArithmeticError (which subclasses Exception)",
      "It subclasses KeyError",
      "It has no parent",
    ],
    answer: 1,
    explain: "ZeroDivisionError is a subclass of ArithmeticError, which is a subclass of Exception.",
  },
  {
    q: "What does catching a base class like OSError also catch?",
    options: [
      "Nothing else",
      "Its subclasses, such as FileNotFoundError and PermissionError",
      "Only OSError exactly",
      "All exceptions",
    ],
    answer: 1,
    explain: "An except for a base class also handles its subclasses, so `except OSError` catches FileNotFoundError, PermissionError, etc.",
  },
  {
    q: "What does a comprehension create that a generator expression does not?",
    options: [
      "A function",
      "A fully materialized collection (list/set/dict) in memory",
      "Lazy evaluation",
      "A tuple",
    ],
    answer: 1,
    explain: "List/set/dict comprehensions build the whole collection immediately; a generator expression yields lazily instead.",
  },
  {
    q: "What does (x for x in range(3)) produce?",
    options: [
      "A tuple",
      "A generator object",
      "A list",
      "A set",
    ],
    answer: 1,
    explain: "Parentheses around a comprehension create a generator, not a tuple. (There is no 'tuple comprehension'.)",
  },
  {
    q: "What is the purpose of finally in resource handling?",
    options: [
      "To catch errors",
      "To guarantee cleanup (close/release) runs whether or not an error occurred",
      "To retry",
      "To log success",
    ],
    answer: 1,
    explain: "finally always runs, making it the place to release resources so they aren't leaked on error paths.",
  },
  {
    q: "What does 'assert x > 0, \"x must be positive\"' do when x is -1?",
    options: [
      "Prints the message and continues",
      "Raises AssertionError with 'x must be positive'",
      "Returns False",
      "Nothing",
    ],
    answer: 1,
    explain: "The condition is False, so AssertionError is raised carrying the given message.",
  },
  {
    q: "Should assert be used to validate untrusted user input in production?",
    options: [
      "Yes, always",
      "No — asserts can be stripped with the -O flag; use explicit checks/raises instead",
      "Only for strings",
      "It doesn't matter",
    ],
    answer: 1,
    explain: "Running Python with -O removes asserts, so they shouldn't guard critical validation; raise explicit exceptions instead.",
  },
  {
    q: "What does [len(w) for w in 'the quick fox'.split()] produce?",
    options: ["[3, 5, 3]", "[3, 3, 3]", "['the','quick','fox']", "[13]"],
    answer: 0,
    explain: "split() gives ['the','quick','fox']; their lengths are 3, 5, 3.",
  },
  {
    q: "What does a try block with multiple statements do when the first line raises?",
    options: [
      "Runs the remaining lines",
      "Skips the rest of the try and jumps to the matching except",
      "Retries the line",
      "Ignores the error",
    ],
    answer: 1,
    explain: "As soon as a line raises, the remaining try statements are skipped and control transfers to a matching except.",
  },
  {
    q: "What does 'try/except Exception as e: logging.exception(e)' provide?",
    options: [
      "Silently ignores errors",
      "Logs the error with its full traceback for later diagnosis",
      "Re-raises immediately",
      "Nothing",
    ],
    answer: 1,
    explain: "logging.exception records the message plus the traceback, preserving diagnostic detail instead of losing it.",
  },
  {
    q: "What does [i for i, c in enumerate('banana') if c == 'a'] return?",
    options: ["[1, 3, 5]", "[0, 2, 4]", "['a','a','a']", "[3]"],
    answer: 0,
    explain: "The 'a' characters in 'banana' sit at indices 1, 3, 5.",
  },
  {
    q: "What is the benefit of raising a specific exception type over a generic one?",
    options: [
      "None",
      "Callers can catch and handle exactly the error they expect",
      "It runs faster",
      "It avoids tracebacks",
    ],
    answer: 1,
    explain: "Specific exception types let callers write targeted handlers, improving clarity and avoiding over-broad catches.",
  }
);
