// ── Chapter 07 — File I/O · expansion pool ──────────────────────────────────
QUESTIONS["07"].push(
  {
    q: "What does mode 'x' do when opening a file?",
    options: [
      "Reads the file",
      "Creates a new file, failing (FileExistsError) if it already exists",
      "Appends to it",
      "Deletes it",
    ],
    answer: 1,
    explain: "Exclusive-creation mode 'x' creates the file and raises FileExistsError if the path already exists — safe against overwrites.",
  },
  {
    q: "What does adding 'b' to a mode (e.g. 'rb') mean?",
    options: [
      "Backup mode",
      "Binary mode — reads/writes bytes instead of text",
      "Buffered mode",
      "Big-endian",
    ],
    answer: 1,
    explain: "The 'b' flag opens the file in binary mode, so you work with bytes objects rather than decoded str.",
  },
  {
    q: "What does mode 'r+' allow?",
    options: [
      "Read only",
      "Reading and writing on an existing file",
      "Appending only",
      "Creating a new file",
    ],
    answer: 1,
    explain: "'r+' opens an existing file for both reading and writing without truncating it.",
  },
  {
    q: "What does f.read(5) do?",
    options: [
      "Reads line 5",
      "Reads at most 5 characters (or bytes) from the current position",
      "Reads 5 lines",
      "Skips 5 characters",
    ],
    answer: 1,
    explain: "Passing a size to read() limits how much is read — here up to 5 characters/bytes.",
  },
  {
    q: "What does f.readline() return?",
    options: [
      "All lines",
      "The next single line, including its trailing newline",
      "The last line",
      "A list",
    ],
    answer: 1,
    explain: "readline() reads and returns one line (with its '\\n'); repeated calls advance through the file.",
  },
  {
    q: "What does f.tell() return?",
    options: [
      "The file name",
      "The current position (offset) in the file",
      "The file size",
      "The number of lines",
    ],
    answer: 1,
    explain: "tell() reports the current byte/character offset, useful with seek() for random access.",
  },
  {
    q: "What does f.seek(0) do?",
    options: [
      "Deletes the file",
      "Moves the read/write position back to the start",
      "Reads the first line",
      "Closes the file",
    ],
    answer: 1,
    explain: "seek(0) repositions to the beginning so you can re-read from the top.",
  },
  {
    q: "What does f.writelines(['a\\n', 'b\\n']) do?",
    options: [
      "Adds newlines automatically",
      "Writes each string as-is with no added separators",
      "Writes a list literal",
      "Errors",
    ],
    answer: 1,
    explain: "writelines writes the strings back to back; it does NOT add newlines, so you must include them yourself.",
  },
  {
    q: "Why pass newline='' when writing CSV with the csv module?",
    options: [
      "For speed",
      "To prevent extra blank rows from double newline translation on some platforms",
      "It's required to open the file",
      "To use UTF-8",
    ],
    answer: 1,
    explain: "The csv module handles line endings itself; newline='' stops the text layer from translating and inserting blank rows (notably on Windows).",
  },
  {
    q: "What must you pass to csv.DictWriter before writing?",
    options: [
      "Nothing",
      "fieldnames (the column headers)",
      "A delimiter only",
      "The number of rows",
    ],
    answer: 1,
    explain: "DictWriter needs fieldnames so it knows the column order; writeheader() then emits that header row.",
  },
  {
    q: "What does csv.reader let you change with the delimiter argument?",
    options: [
      "The encoding",
      "The field separator (e.g. ';' or '\\t' instead of ',')",
      "The quote char only",
      "Nothing",
    ],
    answer: 1,
    explain: "delimiter customizes the separator, so you can parse semicolon- or tab-separated files.",
  },
  {
    q: "What does json.dumps({'a': 1}, sort_keys=True) affect?",
    options: [
      "The values",
      "The output key order (sorted alphabetically)",
      "The indentation",
      "Nothing",
    ],
    answer: 1,
    explain: "sort_keys=True emits object keys in sorted order, which helps produce stable, diff-friendly output.",
  },
  {
    q: "What Python type does a JSON object become after json.loads?",
    options: ["list", "dict", "tuple", "set"],
    answer: 1,
    explain: "A JSON object {...} maps to a Python dict; a JSON array [...] maps to a list.",
  },
  {
    q: "What does JSON null become in Python?",
    options: ["0", "None", "'null'", "False"],
    answer: 1,
    explain: "JSON null deserializes to Python's None.",
  },
  {
    q: "What happens if you json.dump a set (which isn't JSON-serializable)?",
    options: [
      "It works",
      "TypeError — sets aren't serializable; convert to a list first",
      "It becomes null",
      "It becomes a string",
    ],
    answer: 1,
    explain: "JSON has no set type, so dumping one raises TypeError; convert it to a list (or supply a default handler).",
  },
  {
    q: "What does ensure_ascii=False do in json.dump?",
    options: [
      "Breaks the file",
      "Writes non-ASCII characters (like é or 中) directly instead of \\u escapes",
      "Forces ASCII only",
      "Adds indentation",
    ],
    answer: 1,
    explain: "By default json escapes non-ASCII as \\uXXXX; ensure_ascii=False writes the actual UTF-8 characters.",
  },
  {
    q: "What does Path('a/b/c.txt').name return?",
    options: ["'c.txt'", "'c'", "'.txt'", "'a'"],
    answer: 0,
    explain: ".name is the final path component including extension: 'c.txt'.",
  },
  {
    q: "What does Path('a/b/c.txt').stem return?",
    options: ["'c.txt'", "'c'", "'.txt'", "'b'"],
    answer: 1,
    explain: ".stem is the final component without its suffix: 'c'.",
  },
  {
    q: "What does Path('a/b/c.txt').parent return?",
    options: ["Path('a')", "Path('a/b')", "Path('c.txt')", "Path('b')"],
    answer: 1,
    explain: ".parent is the containing directory: Path('a/b').",
  },
  {
    q: "What does Path('data.csv').with_suffix('.txt') return?",
    options: ["Path('data.txt')", "Path('data.csv.txt')", "Path('.txt')", "Error"],
    answer: 0,
    explain: "with_suffix swaps the extension, giving Path('data.txt').",
  },
  {
    q: "What does Path('folder').exists() return?",
    options: [
      "The folder contents",
      "True if the path exists on disk, else False",
      "The size",
      "A list",
    ],
    answer: 1,
    explain: ".exists() checks whether the path exists (file or directory), returning a bool.",
  },
  {
    q: "What does p.is_file() distinguish from p.is_dir()?",
    options: [
      "Nothing",
      "Whether the path is a regular file vs a directory",
      "File size",
      "Read permissions",
    ],
    answer: 1,
    explain: "is_file() is True for regular files; is_dir() is True for directories.",
  },
  {
    q: "What does p.iterdir() yield for a directory p?",
    options: [
      "Recursive contents",
      "The immediate entries (files and subdirs) in that directory",
      "Only files",
      "The parent",
    ],
    answer: 1,
    explain: "iterdir() lists the direct children of the directory (non-recursive).",
  },
  {
    q: "What does p.rglob('*.txt') do that glob('*.txt') does not?",
    options: [
      "Nothing",
      "Searches recursively through all subdirectories",
      "Sorts results",
      "Deletes matches",
    ],
    answer: 1,
    explain: "rglob recurses into subfolders, matching the pattern at any depth; glob only checks the immediate directory.",
  },
  {
    q: "What does Path('note.txt').write_text('hi') do?",
    options: [
      "Appends 'hi'",
      "Opens, writes 'hi' (overwriting), and closes the file in one call",
      "Reads the file",
      "Errors if the file exists",
    ],
    answer: 1,
    explain: "write_text creates/overwrites the file with the given string and handles opening/closing for you.",
  },
  {
    q: "What does p.unlink() do?",
    options: [
      "Renames the file",
      "Deletes the file",
      "Creates a symlink",
      "Reads the file",
    ],
    answer: 1,
    explain: "Path.unlink() removes (deletes) the file. For directories you'd use rmdir() or shutil.rmtree().",
  },
  {
    q: "What does shutil.copy('a.txt', 'b.txt') do?",
    options: [
      "Moves the file",
      "Copies the file's contents to a new path",
      "Deletes a.txt",
      "Links them",
    ],
    answer: 1,
    explain: "shutil.copy duplicates the file to the destination, leaving the original in place.",
  },
  {
    q: "What does shutil.move('a.txt', 'sub/') do?",
    options: [
      "Copies a.txt",
      "Moves (relocates) a.txt into the sub/ directory",
      "Renames sub",
      "Deletes a.txt only",
    ],
    answer: 1,
    explain: "shutil.move relocates the file (like mv), removing it from the source and placing it at the destination.",
  },
  {
    q: "What does os.path.basename('/a/b/c.txt') return?",
    options: ["'/a/b'", "'c.txt'", "'a'", "'.txt'"],
    answer: 1,
    explain: "basename returns the final component of the path: 'c.txt'.",
  },
  {
    q: "What does os.path.splitext('data.csv') return?",
    options: [
      "('data', '.csv')",
      "('data.csv', '')",
      "('data', 'csv')",
      "['data', 'csv']",
    ],
    answer: 0,
    explain: "splitext splits off the extension: ('data', '.csv').",
  },
  {
    q: "What does os.path.getsize(path) return?",
    options: [
      "The number of lines",
      "The file size in bytes",
      "The path length",
      "The modification time",
    ],
    answer: 1,
    explain: "getsize returns the file's size in bytes.",
  },
  {
    q: "Why prefer pathlib over os.path for new code?",
    options: [
      "It's faster",
      "Object-oriented paths with readable operators (/) and methods, cross-platform",
      "os.path is removed",
      "It uses less memory",
    ],
    answer: 1,
    explain: "pathlib offers an object-oriented, readable API (the / operator, .name, .glob) that handles OS differences cleanly.",
  },
  {
    q: "What does opening two files in one with statement look like?",
    options: [
      "with open('a') and open('b'):",
      "with open('a') as fa, open('b') as fb:",
      "with [open('a'), open('b')]:",
      "You can't",
    ],
    answer: 1,
    explain: "You can manage multiple context managers in one with statement separated by commas, each with its own `as`.",
  },
  {
    q: "What does the encoding parameter default to matter for?",
    options: [
      "File size",
      "How bytes are decoded to text; a wrong encoding can corrupt non-ASCII characters",
      "Line count",
      "Nothing",
    ],
    answer: 1,
    explain: "Encoding controls text decoding; being explicit (utf-8) avoids garbled characters from a mismatched platform default.",
  },
  {
    q: "What does 'with open(...) as f' guarantee even if an exception occurs mid-block?",
    options: [
      "The data is saved",
      "The file is closed",
      "The error is caught",
      "The file is deleted",
    ],
    answer: 1,
    explain: "The context manager closes the file on exit, including when an exception propagates out of the block.",
  },
  {
    q: "What does f.flush() do?",
    options: [
      "Closes the file",
      "Forces buffered data to be written out to the OS",
      "Clears the file",
      "Reads remaining data",
    ],
    answer: 1,
    explain: "flush() pushes buffered writes to the operating system without closing the file.",
  },
  {
    q: "What does the csv module's DictReader use as dictionary keys?",
    options: [
      "Row numbers",
      "The values from the header (first) row",
      "Letters A, B, C",
      "The file name",
    ],
    answer: 1,
    explain: "DictReader takes the first row as fieldnames and uses them as keys for every subsequent row's dict.",
  },
  {
    q: "What does reading a CSV give you for each cell's type by default?",
    options: [
      "int",
      "str — you must convert numbers yourself",
      "float",
      "bool",
    ],
    answer: 1,
    explain: "The csv module returns every field as a string; numeric conversion (int/float) is up to you.",
  },
  {
    q: "What does pd.read_csv return?",
    options: ["A list", "A DataFrame", "A dict", "A string"],
    answer: 1,
    explain: "pandas' read_csv parses the file into a DataFrame.",
  },
  {
    q: "What does json.dumps(obj, indent=4) versus json.dumps(obj) change?",
    options: [
      "The data",
      "Pretty-prints with 4-space indentation vs a compact single-line string",
      "The key order",
      "Nothing",
    ],
    answer: 1,
    explain: "indent=4 produces multi-line, human-readable JSON; without it the output is compact on one line.",
  },
  {
    q: "What does p.mkdir(parents=True, exist_ok=True) do?",
    options: [
      "Creates only the leaf directory",
      "Creates the directory and any missing parents, without erroring if it exists",
      "Deletes the directory",
      "Lists the directory",
    ],
    answer: 1,
    explain: "parents=True makes intermediate directories; exist_ok=True suppresses the error if the path already exists.",
  },
  {
    q: "What does reading a file with 'for line in f' leave on each line?",
    options: [
      "No newline",
      "A trailing newline character you often .strip() off",
      "A leading space",
      "Quotes",
    ],
    answer: 1,
    explain: "Each yielded line keeps its trailing '\\n'; call .strip() or .rstrip('\\n') to remove it.",
  },
  {
    q: "What is the risk of mode 'w' on an important file?",
    options: [
      "None",
      "It truncates existing content immediately — data loss if you meant to append",
      "It's read-only",
      "It locks the file forever",
    ],
    answer: 1,
    explain: "'w' erases the file on open; use 'a' to append or 'r+' to edit without truncating.",
  },
  {
    q: "What does p.read_bytes() return?",
    options: [
      "A str",
      "The file contents as a bytes object",
      "A list of lines",
      "An int",
    ],
    answer: 1,
    explain: "read_bytes() reads the whole file in binary, returning bytes — useful for images or other non-text data.",
  },
  {
    q: "What does json.load vs json.loads differ by?",
    options: [
      "Nothing",
      "load reads from a file object; loads reads from a string",
      "loads is for lists only",
      "load returns a string",
    ],
    answer: 1,
    explain: "The trailing 's' means 'string': loads/dumps work with strings, while load/dump work with file objects.",
  },
  {
    q: "What does appending mode do to the file position on open?",
    options: [
      "Starts at the beginning",
      "Positions writes at the end of the existing content",
      "Deletes content",
      "Randomly seeks",
    ],
    answer: 1,
    explain: "Mode 'a' opens with the write position at the end, so new data is added after existing content.",
  }
);
