// ── Chapter 05 — Data Structures ────────────────────────────────────────────
QUESTIONS["05"] = [
  {
    q: "Which of these creates an empty list?",
    options: ["[]", "{}", "()", "set()"],
    answer: 0,
    explain: "[] creates an empty list. {} makes an empty dict, () an empty tuple, and set() an empty set.",
  },
  {
    q: "What does nums.append(9) do to nums = [1, 2]?",
    options: [
      "Returns a new list [1, 2, 9]",
      "Adds 9 to the end, making nums = [1, 2, 9] (in place)",
      "Inserts 9 at the front",
      "Raises an error",
    ],
    answer: 1,
    explain: ".append() mutates the list in place, adding the item to the end. It returns None.",
  },
  {
    q: "What does [1, 2, 3][1] evaluate to?",
    options: ["1", "2", "3", "[2]"],
    answer: 1,
    explain: "Indexing is zero-based, so element at index 1 is the second item, 2.",
  },
  {
    q: "What is the key difference between a list and a tuple?",
    options: [
      "Lists are ordered, tuples are not",
      "Lists are mutable; tuples are immutable",
      "Tuples can't hold strings",
      "There is no difference",
    ],
    answer: 1,
    explain: "Both are ordered sequences, but lists can be changed after creation (mutable) while tuples cannot (immutable).",
  },
  {
    q: "How do you create a single-element tuple containing 5?",
    options: ["(5)", "(5,)", "[5]", "{5}"],
    answer: 1,
    explain: "(5) is just the integer 5 in parentheses. The trailing comma, (5,), is what makes it a one-element tuple.",
  },
  {
    q: "What does a, b = 1, 2 followed by a, b = b, a leave in a?",
    options: ["1", "2", "None", "Error"],
    answer: 1,
    explain: "Tuple unpacking swaps the values: after a, b = b, a, a becomes 2 and b becomes 1.",
  },
  {
    q: "What is a defining property of a set?",
    options: [
      "It keeps items in sorted order",
      "It stores unique, unordered items",
      "It allows duplicate items",
      "It maps keys to values",
    ],
    answer: 1,
    explain: "A set holds unique elements with no defined order and no duplicates. Adding an existing element has no effect.",
  },
  {
    q: "What does {1, 2, 2, 3} evaluate to?",
    options: ["{1, 2, 2, 3}", "{1, 2, 3}", "[1, 2, 3]", "An error"],
    answer: 1,
    explain: "Sets discard duplicates, so the repeated 2 collapses to one, giving {1, 2, 3}.",
  },
  {
    q: "What does {1, 2, 3} & {2, 3, 4} produce?",
    options: ["{1, 2, 3, 4}", "{2, 3}", "{1, 4}", "{}"],
    answer: 1,
    explain: "`&` is set intersection — the elements present in both sets: {2, 3}.",
  },
  {
    q: "What does {1, 2, 3} | {3, 4} produce?",
    options: ["{1, 2, 3, 4}", "{3}", "{1, 2}", "{1, 2, 3, 3, 4}"],
    answer: 0,
    explain: "`|` is set union — all elements from both sets, deduplicated: {1, 2, 3, 4}.",
  },
  {
    q: "How do you create a dictionary mapping 'a' to 1?",
    options: ["{'a': 1}", "{'a', 1}", "['a': 1]", "('a', 1)"],
    answer: 0,
    explain: "Dict literals use key: value pairs inside braces: {'a': 1}. {'a', 1} would be a set.",
  },
  {
    q: "For d = {'x': 10}, what does d['x'] return?",
    options: ["'x'", "10", "{'x': 10}", "KeyError"],
    answer: 1,
    explain: "Indexing a dict by key returns the associated value, so d['x'] is 10.",
  },
  {
    q: "What does d.get('missing') return if 'missing' is not a key?",
    options: ["KeyError", "None", "0", "''"],
    answer: 1,
    explain: ".get() returns None (or a supplied default) for absent keys, avoiding the KeyError that d['missing'] would raise.",
  },
  {
    q: "What does d.get('k', 0) return if 'k' is absent?",
    options: ["None", "0", "KeyError", "'k'"],
    answer: 1,
    explain: "The second argument to .get() is the default returned when the key is missing — here, 0.",
  },
  {
    q: "What does list('abc') return?",
    options: ["['abc']", "['a', 'b', 'c']", "'abc'", "('a','b','c')"],
    answer: 1,
    explain: "list() on a string iterates its characters, producing ['a', 'b', 'c'].",
  },
  {
    q: "What does 'nums[1:3]' return for nums = [10, 20, 30, 40]?",
    options: ["[10, 20]", "[20, 30]", "[20, 30, 40]", "[10, 20, 30]"],
    answer: 1,
    explain: "Slicing [1:3] takes indices 1 and 2 (stop is exclusive): [20, 30].",
  },
  {
    q: "What does nums[::-1] do?",
    options: [
      "Removes the last element",
      "Returns a reversed copy of the sequence",
      "Sorts the sequence",
      "Returns the last element",
    ],
    answer: 1,
    explain: "A step of -1 walks the sequence backward, producing a reversed copy.",
  },
  {
    q: "What does nums[::2] return for nums = [0,1,2,3,4,5]?",
    options: ["[0, 2, 4]", "[1, 3, 5]", "[0,1,2,3,4,5]", "[0, 5]"],
    answer: 0,
    explain: "A step of 2 takes every other element starting from index 0: [0, 2, 4].",
  },
  {
    q: "What does sorted([3, 1, 2]) return?",
    options: ["[3, 2, 1]", "[1, 2, 3]", "None", "It sorts in place"],
    answer: 1,
    explain: "sorted() returns a new sorted list [1, 2, 3] and leaves the original unchanged. (list.sort() sorts in place and returns None.)",
  },
  {
    q: "What does nums.sort() return?",
    options: [
      "A new sorted list",
      "None (it sorts the list in place)",
      "The first element",
      "A reversed list",
    ],
    answer: 1,
    explain: "list.sort() mutates the list in place and returns None. Use sorted() if you want a new list back.",
  },
  {
    q: "What does 'a' in {'a': 1, 'b': 2} check?",
    options: [
      "Whether 'a' is a value",
      "Whether 'a' is a key",
      "Whether the dict is empty",
      "Nothing valid",
    ],
    answer: 1,
    explain: "Membership tests on a dict check its keys, so 'a' in d is True when 'a' is a key.",
  },
  {
    q: "What does d.items() return for a dict?",
    options: [
      "Just the keys",
      "Just the values",
      "A view of (key, value) pairs",
      "The number of items",
    ],
    answer: 2,
    explain: ".items() returns a view of (key, value) tuples, commonly used in `for k, v in d.items():`.",
  },
  {
    q: "Why can a tuple be used as a dictionary key but a list cannot?",
    options: [
      "Tuples are shorter",
      "Dict keys must be hashable; tuples are immutable/hashable, lists are not",
      "Lists are too large",
      "It's an arbitrary rule with no reason",
    ],
    answer: 1,
    explain: "Dict keys must be hashable. Immutable tuples (of hashable items) are hashable; mutable lists are not, so they can't be keys.",
  },
  {
    q: "What does len({'a': 1, 'b': 2}) return?",
    options: ["1", "2", "4", "['a','b']"],
    answer: 1,
    explain: "len() of a dict is the number of key–value pairs, which is 2.",
  },
  {
    q: "What does nums.pop() do with no argument for nums = [1, 2, 3]?",
    options: [
      "Removes and returns the first element",
      "Removes and returns the last element (3)",
      "Empties the list",
      "Returns the length",
    ],
    answer: 1,
    explain: "list.pop() with no index removes and returns the last element, 3, leaving [1, 2].",
  },
  {
    q: "What does the * do in a, *rest = [1, 2, 3, 4]?",
    options: [
      "Multiplies the values",
      "Collects the remaining items into a list (rest = [2, 3, 4])",
      "Raises an error",
      "Ignores the rest",
    ],
    answer: 1,
    explain: "Starred unpacking: a takes 1, and *rest gathers the remaining items into a list [2, 3, 4].",
  },
  {
    q: "Which structure is best for a fast membership test among unique items?",
    options: ["list", "set", "tuple", "string"],
    answer: 1,
    explain: "Sets (and dicts) offer average O(1) membership tests thanks to hashing, versus O(n) for lists/tuples.",
  },
  {
    q: "What does list(range(3)) produce?",
    options: ["[0, 1, 2]", "[1, 2, 3]", "[0, 1, 2, 3]", "range(3)"],
    answer: 0,
    explain: "range(3) yields 0, 1, 2, and list() materializes them into [0, 1, 2].",
  },
  {
    q: "What does 'nums[1:3] = [9]' do to nums = [1, 2, 3, 4]?",
    options: [
      "Raises an error",
      "Replaces indices 1–2 with 9, giving [1, 9, 4]",
      "Appends 9",
      "Deletes everything",
    ],
    answer: 1,
    explain: "Slice assignment replaces the [1:3] segment (values 2 and 3) with the contents of [9], producing [1, 9, 4].",
  },
  {
    q: "What does d.keys() return?",
    options: [
      "A list of values",
      "A view of the dictionary's keys",
      "The number of keys",
      "A sorted list of keys",
    ],
    answer: 1,
    explain: ".keys() returns a dynamic view of the dict's keys, iterable in insertion order (Python 3.7+).",
  },
];
